import {
  NO_NOTE,
  NOTE_CHANGE_SEMITONES,
  NOTE_MIN_DURATION_MS,
  NOTE_OFF_THRESHOLD,
  NOTE_ON_THRESHOLD,
  PITCH_CONFIDENCE_THRESHOLD,
  PITCH_MAX_LAG,
  PITCH_OCTAVE_GUARD,
  PITCH_MIN_LAG,
  PITCH_SAMPLE_RATE,
} from '../../audio/fastledPitch'

const f = (value: number) => (Number.isInteger(value) ? `${value}.0f` : `${value}f`)

/**
 * The Pitch Detect firmware: FastLED's Pitch and Note arithmetic run against
 * `Processor::getSample()`, the same code `src/audio/fastledPitch.ts` runs in
 * the preview. FastLED's own `Pitch` detector needs 1102 samples per chunk and
 * its I2S input supplies 512, so it can never voice; this runs the identical
 * algorithm over the lags that fit. Key detection is FastLED's, through
 * `Processor::onKey`. Constants come from the TypeScript module so the two
 * cannot drift. Confidence divides the autocorrelation peak by the zero-lag
 * power, where FastLED's raw peak needs a near full-scale signal to reach 0.5.
 */
export function pitchGlobalsCpp(): string[] {
  return [
    '// Pitch Detect: FastLED Pitch/Note arithmetic over the 512-sample chunk (see pitchHelperCpp.ts).',
    'float _audioPitchHz = 0.0f, _audioPitchConf = 0.0f, _audioPitchVelocity = 0.0f;',
    'int   _audioPitchNote = 0;',
    'bool  _audioPitchNoteOn = false;',
    'int   _audioKeyRoot = 0;',
    'bool  _audioKeyMinor = false;',
    'float _audioKeyConf = 0.0f;',
  ]
}

export function pitchHelperCpp(): string[] {
  return [
    `#define STUDIO_PITCH_MIN_LAG ${PITCH_MIN_LAG}`,
    `#define STUDIO_PITCH_MAX_LAG ${PITCH_MAX_LAG}`,
    `#define STUDIO_PITCH_SAMPLES ${PITCH_MAX_LAG * 2 + 8}`,
    'static int _pitchNote = ' + NO_NOTE + ', _pitchVelocity = 0;',
    'static bool _pitchActive = false;',
    'static uint32_t _pitchOnMs = 0, _pitchStamp = 0;',
    '',
    'static float _pitchDetect(const fl::i16* pcm, size_t n, float* confOut) {',
    '  static float x[STUDIO_PITCH_SAMPLES];',
    '  static float acf[STUDIO_PITCH_MAX_LAG + 1];',
    '  *confOut = 0.0f;',
    '  if (n < (size_t)(STUDIO_PITCH_MAX_LAG * 2)) return 0.0f;',
    '  if (n > STUDIO_PITCH_SAMPLES) n = STUDIO_PITCH_SAMPLES;',
    '  float power = 0.0f;',
    '  for (size_t i = 0; i < n; ++i) { x[i] = (float)pcm[i] / 32768.0f; power += x[i] * x[i]; }',
    '  power /= (float)n;',
    '  if (power < 1e-12f) return 0.0f;',
    '  for (int i = 0; i <= STUDIO_PITCH_MAX_LAG; ++i) acf[i] = 0.0f;',
    '  for (int lag = STUDIO_PITCH_MIN_LAG; lag <= STUDIO_PITCH_MAX_LAG; ++lag) {',
    '    float sum = 0.0f;',
    '    int valid = 0;',
    '    for (size_t i = 0; i + lag < n; ++i) { sum += x[i] * x[i + lag]; ++valid; }',
    '    if (valid > 0) acf[lag] = sum / (float)valid;',
    '  }',
    '  int best = 0;',
    '  float maxValue = -1.0f;',
    '  for (int lag = STUDIO_PITCH_MIN_LAG; lag <= STUDIO_PITCH_MAX_LAG; ++lag) {',
    '    if (acf[lag] > maxValue && acf[lag] > 0.0f) { maxValue = acf[lag]; best = lag; }',
    '  }',
    '  if (best <= 0) return 0.0f;',
    '  // Octave guard: the smallest local peak within 90% of the highest.',
    '  for (int lag = STUDIO_PITCH_MIN_LAG; lag < best; ++lag) {',
    '    float prev = lag > STUDIO_PITCH_MIN_LAG ? acf[lag - 1] : -1.0e9f;',
    `    if (acf[lag] >= maxValue * ${f(PITCH_OCTAVE_GUARD)} && acf[lag] >= prev && acf[lag] >= acf[lag + 1]) { best = lag; break; }`,
    '  }',
    '  float peak = acf[best];',
    '  float conf = fmaxf(0.0f, fminf(1.0f, peak / power));',
    '  int window = best / 10 > 2 ? best / 10 : 2;',
    '  float neighbours = 0.0f;',
    '  int count = 0;',
    '  for (int o = -window; o <= window; ++o) {',
    '    if (o == 0) continue;',
    '    int lag = best + o;',
    '    if (lag >= STUDIO_PITCH_MIN_LAG && lag <= STUDIO_PITCH_MAX_LAG) { neighbours += fmaxf(0.0f, acf[lag]); ++count; }',
    '  }',
    '  if (count > 0) {',
    '    float avg = neighbours / (float)count;',
    '    if (avg > 1e-6f) conf *= 0.7f + 0.3f * fminf(1.0f, (peak - avg) / avg);',
    '  }',
    '  *confOut = conf;',
    `  if (conf < ${f(PITCH_CONFIDENCE_THRESHOLD)}) return 0.0f;`,
    `  return ${f(PITCH_SAMPLE_RATE)} / (float)best;`,
    '}',
    '',
    'static int _pitchMidi(float hz) {',
    '  if (hz <= 0.0f) return ' + NO_NOTE + ';',
    '  int m = (int)(69.0f + 12.0f * (logf(hz / 440.0f) / logf(2.0f)) + 0.5f);',
    '  return m < 0 ? 0 : (m > 127 ? 127 : m);',
    '}',
    '',
    'static int _pitchVelocityOf(float rms, float conf) {',
    '  int v = (int)(fminf(1.0f, fmaxf(0.0f, rms)) * conf * 126.0f) + 1;',
    '  return v < 1 ? 1 : (v > 127 ? 127 : v);',
    '}',
    '',
    'static void _audioPitchClear() {',
    '  _audioPitchHz = _audioPitchConf = _audioPitchVelocity = 0.0f;',
    '  _audioPitchNote = 0;',
    '  _audioPitchNoteOn = false;',
    '  _pitchNote = ' + NO_NOTE + ';',
    '  _pitchVelocity = 0;',
    '  _pitchActive = false;',
    '}',
    '',
    '// One step per new chunk: FastLED Pitch, then the Note state machine.',
    'static void _audioPitchStep() {',
    '  _audioPitchNoteOn = false;',
    '  const fl::audio::Sample& sample = _audioProcessor->getSample();',
    '  if (!sample.isValid() || sample.timestamp() == _pitchStamp) return;',
    '  _pitchStamp = sample.timestamp();',
    '  float conf = 0.0f;',
    '  const auto& pcm = sample.pcm();',
    '  float hz = _pitchDetect(pcm.data(), pcm.size(), &conf);',
    '  bool voiced = hz > 0.0f;',
    '  float rms = sample.rms();',
    '  uint32_t now = millis();',
    '  _audioPitchHz = hz;',
    '  _audioPitchConf = conf;',
    '  if (!_pitchActive) {',
    `    if (conf >= ${f(NOTE_ON_THRESHOLD)} && hz > 0.0f) {`,
    '      _pitchNote = _pitchMidi(hz);',
    '      _pitchVelocity = _pitchVelocityOf(rms, conf);',
    '      _pitchActive = true;',
    '      _pitchOnMs = now;',
    '      _audioPitchNoteOn = true;',
    '    }',
    `  } else if (conf < ${f(NOTE_OFF_THRESHOLD)} || !voiced) {`,
    `    if (now - _pitchOnMs >= ${NOTE_MIN_DURATION_MS}) {`,
    `      _pitchNote = ${NO_NOTE};`,
    '      _pitchVelocity = 0;',
    '      _pitchActive = false;',
    '    }',
    `  } else if (conf >= ${f(NOTE_ON_THRESHOLD)}) {`,
    '    int next = _pitchMidi(hz);',
    `    if (abs(next - _pitchNote) >= ${NOTE_CHANGE_SEMITONES}) {`,
    '      _pitchNote = next;',
    '      _pitchVelocity = _pitchVelocityOf(rms, conf);',
    '      _pitchOnMs = now;',
    '      _audioPitchNoteOn = true;',
    '    }',
    '  }',
    `  _audioPitchNote = _pitchNote == ${NO_NOTE} ? 0 : _pitchNote;`,
    '  _audioPitchVelocity = (float)_pitchVelocity / 127.0f;',
    '}',
  ]
}
