/**
 * A sketch whose only job is to name one button on a remote.
 *
 * Temporary, like touch calibration: it drives the receiver pin, prints one
 * versioned `FLS_IR` line per decoded frame, and stays until the project is
 * uploaded again. It is not cached as the project's last sketch.
 *
 * The include and decoder macros come from `irRemoteCpp`, the same block a
 * project sketch will use. Learning does not know the remote yet, so every
 * protocol the app can save is enabled. A project sketch enables only the
 * families its keys actually use.
 */

import { irLearnHeader, irRemoteBeginLine } from './irRemoteCpp'

export interface IrLearnSketchTarget {
  pin: number
}

export function generateIrLearnSketch(target: IrLearnSketchTarget): string {
  const pin = Math.max(0, Math.min(255, Math.trunc(target.pin)))
  return `// IR learn — generated by Design Studio for FastLED.
//
// A temporary measuring sketch, not your project. It prints one line per
// decoded frame at 115200. Upload the project again once the key is saved.
${irLearnHeader()}

static constexpr uint8_t IR_LEARN_PIN = ${pin};

void setup() {
  Serial.begin(115200);
  delay(200);
  ${irRemoteBeginLine('IR_LEARN_PIN')}
  Serial.println(F("FLS_IR ready pin=${pin}"));
}

void loop() {
  if (!IrReceiver.decode()) return;
  const bool repeat = (IrReceiver.decodedIRData.flags & IRDATA_FLAGS_IS_REPEAT) != 0;
  if (IrReceiver.decodedIRData.protocol != UNKNOWN) {
    Serial.printf("FLS_IR v=1 protocol=%s address=0x%lX command=0x%lX repeat=%d\\n",
                  getProtocolString(IrReceiver.decodedIRData.protocol),
                  (unsigned long)IrReceiver.decodedIRData.address,
                  (unsigned long)IrReceiver.decodedIRData.command,
                  repeat ? 1 : 0);
  }
  IrReceiver.resume();
}
`
}
