/**
 * A sketch whose only job is to name one button on a remote.
 *
 * Temporary, like touch calibration: it drives the receiver pin, prints one
 * versioned `FLS_IR` line per decoded frame, and stays until the project is
 * uploaded again. It is not cached as the project's last sketch.
 *
 * Decoders for every protocol the app can save are switched on before the
 * include. Variants such as NEC2, Apple and Onkyo share the NEC decoder; the
 * line still prints the library's protocol name, which the app canonicalizes.
 */

export interface IrLearnSketchTarget {
  pin: number
}

const DECODE_MACROS = [
  'DECODE_NEC',
  'DECODE_PANASONIC',
  'DECODE_KASEIKYO',
  'DECODE_DENON',
  'DECODE_SHARP',
  'DECODE_SONY',
  'DECODE_RC5',
  'DECODE_RC6',
  'DECODE_SAMSUNG',
  'DECODE_LG',
  'DECODE_JVC',
] as const

export function generateIrLearnSketch(target: IrLearnSketchTarget): string {
  const pin = Math.max(0, Math.min(255, Math.trunc(target.pin)))
  const macros = DECODE_MACROS.map((name) => `#define ${name}`).join('\n')
  return `// IR learn — generated by Design Studio for FastLED.
//
// A temporary measuring sketch, not your project. It prints one line per
// decoded frame at 115200. Upload the project again once the key is saved.
${macros}
#include <IRremote.hpp>

static constexpr uint8_t IR_LEARN_PIN = ${pin};

void setup() {
  Serial.begin(115200);
  delay(200);
  IrReceiver.begin(IR_LEARN_PIN, DISABLE_LED_FEEDBACK);
  Serial.println(F("FLS_IR ready pin=${pin}"));
}

void loop() {
  if (!IrReceiver.decode()) return;
  const bool repeat = (IrReceiver.decodedIRData.flags & IRDATA_FLAGS_IS_REPEAT) != 0;
  if (IrReceiver.decodedIRData.protocol != UNKNOWN) {
    Serial.printf("FLS_IR v=1 protocol=%s address=0x%lX command=0x%lX repeat=%d\\n",
                  getProtocolString(IrReceiver.decodedIRData.protocol),
                  (unsigned long)IrReceiver.decodedIRData.address,
                  (unsigned long)IrReceiver.decodedIRData.command,
                  repeat ? 1 : 0);
  }
  IrReceiver.resume();
}
`
}
