// Generates the ESP32-S3 player sketch that:
//   - plays MP3 from SD card via I2S
//   - reads the companion .show file
//   - executes LED commands at the right timestamps in sync with audio position

export interface PlayerConfig {
  ledWidth:    number
  ledHeight:   number
  ledDataPin:  number
  chipset:     string
  colorOrder:  string
  sdCsPin:     number
  i2sBclk:     number   // I2S bit clock pin
  i2sLrc:      number   // I2S left/right clock (word select)
  i2sDout:     number   // I2S data out to DAC
  maxVolume:   number   // 0-21 for MAX98357A
}

const DEFAULTS: PlayerConfig = {
  ledWidth: 16, ledHeight: 16, ledDataPin: 18,
  chipset: 'WS2812B', colorOrder: 'GRB',
  sdCsPin: 5,
  i2sBclk: 26, i2sLrc: 25, i2sDout: 22,
  maxVolume: 18,
}

// Minimal node shape so this stays decoupled from the graph store.
interface ConfigNode { data: { nodeType: string; properties: Record<string, unknown> } }

/**
 * Derive the player's hardware config from the graph: LED matrix settings come
 * from the MatrixOutput node, SD + I2S audio pins from the SDCard node. Used by
 * the music-sync upload flow, where the SDCard is wired into MatrixOutput.
 */
export function playerConfigFromGraph(nodes: ConfigNode[]): Partial<PlayerConfig> {
  const mo = nodes.find((n) => n.data.nodeType === 'MatrixOutput')?.data.properties ?? {}
  const sd = nodes.find((n) => n.data.nodeType === 'SDCard')?.data.properties ?? {}
  const num = (v: unknown, d: number) => (v === undefined || v === null ? d : Number(v))
  const str = (v: unknown, d: string) => (v === undefined || v === null ? d : String(v))
  return {
    ledWidth:   num(mo.width, DEFAULTS.ledWidth),
    ledHeight:  num(mo.height, DEFAULTS.ledHeight),
    ledDataPin: num(mo.dataPin, DEFAULTS.ledDataPin),
    chipset:    str(mo.chipset, DEFAULTS.chipset),
    colorOrder: str(mo.colorOrder, DEFAULTS.colorOrder),
    sdCsPin:    num(sd.sdCsPin, DEFAULTS.sdCsPin),
    i2sBclk:    num(sd.i2sBclk, DEFAULTS.i2sBclk),
    i2sLrc:     num(sd.i2sLrc, DEFAULTS.i2sLrc),
    i2sDout:    num(sd.i2sDout, DEFAULTS.i2sDout),
    maxVolume:  num(sd.maxVolume, DEFAULTS.maxVolume),
  }
}

export function generatePlayerSketch(cfg: Partial<PlayerConfig> = {}): string {
  const c = { ...DEFAULTS, ...cfg }
  const numLeds = c.ledWidth * c.ledHeight

  return `// FastLED Studio — Music-Sync Player
// Generated by FastLED Studio. Requires:
//   - ESP32-audioI2S  (schreibfaul1/ESP32-audioI2S on GitHub)
//   - FastLED
//   - SD (built-in Arduino)
// Hardware: SD card on SPI, I2S DAC (MAX98357A or PCM5102) on pins below.

#include <FastLED.h>
#include <SD.h>
#include <SPI.h>
#include <Audio.h>       // ESP32-audioI2S

// ── Pin config ────────────────────────────────────────────────────────────────
#define LED_DATA_PIN  ${c.ledDataPin}
#define WIDTH         ${c.ledWidth}
#define HEIGHT        ${c.ledHeight}
#define NUM_LEDS      ${numLeds}
#define SD_CS         ${c.sdCsPin}
#define I2S_BCLK      ${c.i2sBclk}
#define I2S_LRC       ${c.i2sLrc}
#define I2S_DOUT      ${c.i2sDout}

// ── Show file binary format ───────────────────────────────────────────────────
// Header: magic(4) + version(1) + bpm_x10(2) + duration_ms(4) + event_count(4)
// Event:  t_ms(4) + cmd(1) + param_count(1) + params[](float32 * N)
#define CMD_SET_PATTERN    0
#define CMD_SET_PALETTE    1
#define CMD_SET_SPEED      2
#define CMD_SET_BRIGHTNESS 3
#define CMD_BEAT_FLASH     4
#define CMD_TRANSITION     5

struct ShowEvent {
  uint32_t t;
  uint8_t  cmd;
  uint8_t  paramCount;
  float    params[4];
};

// ── Globals ───────────────────────────────────────────────────────────────────
CRGB leds[NUM_LEDS];
Audio audio;

ShowEvent* showEvents = nullptr;
uint32_t   eventCount = 0;
uint32_t   eventIdx   = 0;
float      animSpeed  = 1.0f;
uint8_t    patternId  = 2;        // default: Plasma
uint8_t    paletteId  = 0;        // default: Rainbow
float      flashLevel = 0.0f;
float      transProgress = 1.0f;  // 1 = no transition in progress

// ── Palette helper ────────────────────────────────────────────────────────────
CRGB samplePalette(uint8_t palId, uint8_t index) {
  switch (palId) {
    case 1:  return ColorFromPalette(OceanColors_p,   index);
    case 2:  return ColorFromPalette(LavaColors_p,    index);
    case 3:  return ColorFromPalette(ForestColors_p,  index);
    case 4:  return ColorFromPalette(HeatColors_p,    index);
    case 5:  return ColorFromPalette(PartyColors_p,   index);
    default: return ColorFromPalette(RainbowColors_p, index);
  }
}

// ── Pattern renderers ─────────────────────────────────────────────────────────
void renderPattern(float t) {
  switch (patternId) {
    case 0:  // SolidColor
      fill_solid(leds, NUM_LEDS, samplePalette(paletteId, 0));
      break;
    case 1:  // NoiseField
      for (int y = 0; y < HEIGHT; y++)
        for (int x = 0; x < WIDTH; x++) {
          float v = (sin(x * 0.5f + t * animSpeed) + cos(y * 0.5f + t * animSpeed * 0.7f)) * 0.5f;
          leds[y * WIDTH + x] = samplePalette(paletteId, (uint8_t)((v + 1) * 100 + t * 10));
        }
      break;
    case 2:  // Plasma
      for (int y = 0; y < HEIGHT; y++)
        for (int x = 0; x < WIDTH; x++) {
          float v = sin(x / 3.0f + t * animSpeed)
                  + sin(y / 3.0f + t * animSpeed * 0.8f)
                  + sin((x + y) / 5.0f + t * animSpeed * 0.6f);
          leds[y * WIDTH + x] = samplePalette(paletteId, (uint8_t)(v * 45 + t * 20));
        }
      break;
    case 3:  // Fire
    case 4: { // Fire2012
      static uint8_t heat[${c.ledHeight}][${c.ledWidth}] = {};
      for (int y = 0; y < HEIGHT; y++)
        for (int x = 0; x < WIDTH; x++)
          heat[y][x] = qsub8(heat[y][x], random8(0, 12));
      for (int y = 0; y < HEIGHT - 2; y++)
        for (int x = 0; x < WIDTH; x++)
          heat[y][x] = (heat[y+1][x] + heat[y+2][max(0,x-1)] + heat[y+2][x] + heat[y+2][min(WIDTH-1,x+1)]) / 4;
      for (int x = 0; x < WIDTH; x++)
        if (random8() < 120) heat[HEIGHT-1][x] = qadd8(heat[HEIGHT-1][x], random8(160, 255));
      for (int y = 0; y < HEIGHT; y++)
        for (int x = 0; x < WIDTH; x++)
          leds[y * WIDTH + x] = HeatColor(heat[y][x]);
      break;
    }
    case 6:  // RadialBurst
      for (int y = 0; y < HEIGHT; y++)
        for (int x = 0; x < WIDTH; x++) {
          float d = sqrt((x-WIDTH/2.0f)*(x-WIDTH/2.0f)+(y-HEIGHT/2.0f)*(y-HEIGHT/2.0f))
                    / sqrt(WIDTH*WIDTH/4.0f + HEIGHT*HEIGHT/4.0f);
          float w = (sin((d * 8 - t * animSpeed * 3) * 3.14159f) + 1) / 2.0f;
          leds[y * WIDTH + x] = samplePalette(paletteId, (uint8_t)(w * 255));
        }
      break;
    case 7:  // Spiral
      for (int y = 0; y < HEIGHT; y++)
        for (int x = 0; x < WIDTH; x++) {
          float d = sqrt((x-WIDTH/2.0f)*(x-WIDTH/2.0f)+(y-HEIGHT/2.0f)*(y-HEIGHT/2.0f))
                    / sqrt(WIDTH*WIDTH/4.0f + HEIGHT*HEIGHT/4.0f);
          float a = atan2(y-HEIGHT/2.0f, x-WIDTH/2.0f);
          float s = (a + d * 12.57f - t * animSpeed * 3.14159f) * 2;
          leds[y * WIDTH + x] = samplePalette(paletteId, (uint8_t)((sin(s)+1)/2.0f*255));
        }
      break;
    case 11: // GradientFrame
    default:
      for (int i = 0; i < NUM_LEDS; i++)
        leds[i] = samplePalette(paletteId, (uint8_t)(i * 255 / NUM_LEDS + t * 10));
      break;
  }
}

// ── Show file loader ──────────────────────────────────────────────────────────
bool loadShowFile(const char* path) {
  File f = SD.open(path, FILE_READ);
  if (!f) return false;

  uint8_t header[15];
  f.read(header, 15);
  if (header[0]!='S'||header[1]!='H'||header[2]!='O'||header[3]!='W') { f.close(); return false; }

  eventCount = ((uint32_t)header[11]) | ((uint32_t)header[12]<<8) |
               ((uint32_t)header[13]<<16) | ((uint32_t)header[14]<<24);
  if (showEvents) free(showEvents);
  showEvents = (ShowEvent*)malloc(eventCount * sizeof(ShowEvent));
  if (!showEvents) { f.close(); return false; }

  for (uint32_t i = 0; i < eventCount; i++) {
    uint8_t evBuf[6]; f.read(evBuf, 6);
    showEvents[i].t = ((uint32_t)evBuf[0])|((uint32_t)evBuf[1]<<8)|
                      ((uint32_t)evBuf[2]<<16)|((uint32_t)evBuf[3]<<24);
    showEvents[i].cmd        = evBuf[4];
    showEvents[i].paramCount = evBuf[5];
    for (uint8_t p = 0; p < showEvents[i].paramCount && p < 4; p++) {
      uint8_t fb[4]; f.read(fb, 4);
      uint32_t raw = ((uint32_t)fb[0])|((uint32_t)fb[1]<<8)|
                     ((uint32_t)fb[2]<<16)|((uint32_t)fb[3]<<24);
      memcpy(&showEvents[i].params[p], &raw, 4);
    }
  }
  f.close();
  eventIdx = 0;
  return true;
}

// ── Event dispatcher ──────────────────────────────────────────────────────────
void applyEvent(const ShowEvent& ev) {
  switch (ev.cmd) {
    case CMD_SET_PATTERN:    patternId  = (uint8_t)ev.params[0]; break;
    case CMD_SET_PALETTE:    paletteId  = (uint8_t)ev.params[0]; break;
    case CMD_SET_SPEED:      animSpeed  = ev.params[0]; break;
    case CMD_SET_BRIGHTNESS: FastLED.setBrightness((uint8_t)ev.params[0]); break;
    case CMD_BEAT_FLASH:     flashLevel = ev.params[0] / 255.0f; break;
    case CMD_TRANSITION:     transProgress = 0.0f; break;
  }
}

// ── Setup ─────────────────────────────────────────────────────────────────────
void setup() {
  Serial.begin(115200);

  FastLED.addLeds<${c.chipset}, LED_DATA_PIN, ${c.colorOrder}>(leds, NUM_LEDS);
  FastLED.setBrightness(180);

  if (!SD.begin(SD_CS)) { Serial.println("SD mount failed"); while(1); }

  audio.setPinout(I2S_BCLK, I2S_LRC, I2S_DOUT);
  audio.setVolume(${c.maxVolume});

  // Play the first .mp3 found in /music/
  File root = SD.open("/music");
  File entry = root.openNextFile();
  while (entry) {
    String name = entry.name();
    if (name.endsWith(".mp3") || name.endsWith(".MP3")) {
      String showPath = "/shows/" + name.substring(0, name.lastIndexOf('.')) + ".show";
      loadShowFile(showPath.c_str());
      audio.connecttoFS(SD, ("/music/" + name).c_str());
      Serial.printf("Playing: %s\\n", name.c_str());
      break;
    }
    entry = root.openNextFile();
  }
}

// ── Loop ──────────────────────────────────────────────────────────────────────
void loop() {
  audio.loop();

  uint32_t posMs = audio.getFilePos() > 0
    ? (uint32_t)(audio.getFilePos() * 8.0f / audio.getBitRate() * 1000.0f)
    : 0;

  // Dispatch all events whose timestamp has passed
  while (eventIdx < eventCount && showEvents[eventIdx].t <= posMs) {
    applyEvent(showEvents[eventIdx]);
    eventIdx++;
  }

  float t = posMs / 1000.0f;
  renderPattern(t);

  // Beat flash overlay
  if (flashLevel > 0.01f) {
    for (int i = 0; i < NUM_LEDS; i++) {
      leds[i].r = qadd8(leds[i].r, (uint8_t)((255 - leds[i].r) * flashLevel));
      leds[i].g = qadd8(leds[i].g, (uint8_t)((255 - leds[i].g) * flashLevel));
      leds[i].b = qadd8(leds[i].b, (uint8_t)((255 - leds[i].b) * flashLevel));
    }
    flashLevel *= 0.82f;  // decay
  }

  FastLED.show();
  FastLED.delay(16);  // ~60 fps
}
`
}
