// Generates the ESP32 "provisioner" sketch — a tiny firmware that loads songs
// (/music) and shows (/shows) onto the SD card over USB serial.
//
// NOTHING CALLS THIS ANY MORE. The player carries the same receiver itself, so
// the upload is one build and one flash instead of three. This file is kept
// only until that merged path is hardware-validated; delete it (and its tests)
// once it is, rather than letting a second copy of the protocol drift.
//
// ── Wire protocol (host → device) ─────────────────────────────────────────────
// Newline-terminated ASCII control lines, with raw binary payloads in between.
// The device drives flow control by ACKing each chunk, so the host never
// overruns the serial RX buffer while the SD write (slower than USB CDC) catches
// up:
//
//   boot            device prints "READY" once the SD card mounts (else "ERR …")
//   PING            device replies "READY" (re-probe — the boot "READY" may have
//                   been missed if the host opened the port after reset)
//   PUT <path> <n>  open <path> for writing (creating its parent dir); device
//                   replies "OK", then the host streams <n> bytes in blocks of at
//                   most PROVISION_CHUNK, the device replying "A" after each block
//                   is written, and "DONE" once all <n> bytes are stored.
//                   <path> MAY CONTAIN SPACES — song titles routinely do — so
//                   the device splits this line on its *last* space. <n> is
//                   therefore the only field that must be space-free.
//   END             device replies "BYE"; provisioning is complete.
//
// The Python helper (backend/) implements the host side; keep the two in sync.

import { sanitizePin } from './hardwarePins'

export interface ProvisionerConfig {
  /** SD SPI pins from the SDCard hardware part. */
  sdCsPin: number
  sdSckPin: number
  sdMisoPin: number
  sdMosiPin: number
}

// GPIO10 avoids colliding with MatrixOutput's default LED data pin (GPIO5).
const DEFAULTS: ProvisionerConfig = {
  sdCsPin: 10,
  sdSckPin: 12,
  sdMisoPin: 13,
  sdMosiPin: 11,
}

/** Transfer block size, in bytes — must match the host sender in the backend. */
export const PROVISION_CHUNK = 4096

/** Link speed the host negotiates after the handshake, falling back to 115200.
 *  A 7.5 MB song takes ~11 minutes at 115200 and well under two at this rate. */
export const PROVISION_BAUD = 921600

/** Device UART receive buffer. Comfortably larger than one block so the driver
 *  keeps absorbing while the previous block's SD write completes. */
export const PROVISION_RX_BUFFER = 8192

export function generateProvisionerSketch(cfg: Partial<ProvisionerConfig> = {}): string {
  const c = {
    ...DEFAULTS,
    ...cfg,
    sdCsPin: sanitizePin(cfg.sdCsPin, DEFAULTS.sdCsPin),
    sdSckPin: sanitizePin(cfg.sdSckPin, DEFAULTS.sdSckPin),
    sdMisoPin: sanitizePin(cfg.sdMisoPin, DEFAULTS.sdMisoPin),
    sdMosiPin: sanitizePin(cfg.sdMosiPin, DEFAULTS.sdMosiPin),
  }
  return `// Design Studio for FastLED — SD Provisioner
// Receives files over USB serial and writes them to the SD card, so the studio
// can load /music and /shows before the player sketch is flashed. Generated by
// Design Studio for FastLED — see provisionerSketchGenerator.ts for the wire protocol.

#include <SD.h>
#include <SPI.h>

#define SD_CS  ${c.sdCsPin}
#define SD_SCK  ${c.sdSckPin}
#define SD_MISO  ${c.sdMisoPin}
#define SD_MOSI  ${c.sdMosiPin}
#define CHUNK      ${PROVISION_CHUNK}
#define LINE_TIMEOUT_MS      2000
#define BLOCK_TIMEOUT_MS     3000
#define RX_BUFFER  ${PROVISION_RX_BUFFER}

// Create the parent directory of \`path\` (one level is enough for /music, /shows).
void ensureDir(const String& path) {
  int slash = path.lastIndexOf('/');
  if (slash <= 0) return;
  String dir = path.substring(0, slash);
  if (dir.length() && !SD.exists(dir)) SD.mkdir(dir);
}

// Read one '\\n'-terminated control line, ignoring '\\r'.
// Bounded: an idle line returns an empty string rather than waiting for a
// byte that may never come, so a host that goes away leaves the board
// responsive instead of wedged.
String readLine(uint32_t timeoutMs) {
  String s;
  uint32_t last = millis();
  for (;;) {
    if (!Serial.available()) {
      if (millis() - last > timeoutMs) return String();
      continue;
    }
    char ch = Serial.read();
    if (ch == '\\n') break;
    if (ch != '\\r') s += ch;
    last = millis();
  }
  return s;
}

void setup() {
  // A whole song crosses this link, so the RX buffer has to absorb a full
  // block while the SD write of the previous one is still finishing. The
  // 256-byte default would overrun the moment the link is raised below.
  // Must precede begin() — ESP32 sizes the driver's buffer at init.
  Serial.setRxBufferSize(RX_BUFFER);
  Serial.begin(115200);
  while (!Serial) { /* wait for USB CDC */ }
  delay(200);
  SPI.begin(SD_SCK, SD_MISO, SD_MOSI, SD_CS);
  if (!SD.begin(SD_CS)) { Serial.println("ERR sd-mount-failed"); for (;;) {} }
  Serial.println("READY");
}

void loop() {
  String line = readLine(LINE_TIMEOUT_MS);
  if (line == "PING") {
    Serial.println("READY");
  } else if (line.startsWith("PUT ")) {
    // Split on the LAST space, not the first: the size is a single trailing
    // token but the path is user-derived and routinely contains spaces
    // ("/music/Uplifting Trance.mp3"). Splitting on the first space parsed the
    // path as "/music/Uplifting" and the size as 0, so the device opened a
    // truncated file, answered OK, skipped the write loop entirely and replied
    // DONE — while the host streamed megabytes at a device that had stopped
    // listening, and reported a lost ack at byte 0.
    int sp = line.lastIndexOf(' ');
    if (sp < 4) { Serial.println("ERR bad-put"); return; }
    String path = line.substring(4, sp);
    uint32_t size = (uint32_t) strtoul(line.substring(sp + 1).c_str(), nullptr, 10);
    // A zero size means the size token did not parse. Refusing here surfaces it
    // as a clean "device refused" on the host; accepting it silently desyncs
    // the stream, which is far harder to diagnose.
    if (size == 0) { Serial.println("ERR bad-size"); return; }

    ensureDir(path);
    if (SD.exists(path)) SD.remove(path);
    File f = SD.open(path, FILE_WRITE);
    if (!f) { Serial.println("ERR open-failed"); return; }
    Serial.println("OK");

    // static, not a local: a 4 KB block on the loop task's 8 KB stack is too
    // close to the edge, and only one transfer is ever in flight.
    static uint8_t buf[CHUNK];
    uint32_t remaining = size;
    while (remaining > 0) {
      uint32_t want = remaining < CHUNK ? remaining : CHUNK;
      uint32_t got = 0;
      uint32_t last = millis();
      while (got < want) {
        if (!Serial.available()) {
          // Bounded for the same reason: a byte lost to a USB hiccup costs
          // one transfer instead of a board that never answers again.
          if (millis() - last > BLOCK_TIMEOUT_MS) {
            f.close();
            SD.remove(path);   // a truncated file is worse than no file
            Serial.printf("ERR timeout %lu/%lu\\n",
                          (unsigned long) (size - remaining + got), (unsigned long) size);
            return;
          }
          continue;
        }
        got += Serial.readBytes(buf + got, want - got);
        last = millis();
      }
      f.write(buf, want);
      remaining -= want;
      Serial.println("A");   // ack: block written, send the next
    }
    f.close();
    Serial.println("DONE");
  } else if (line.startsWith("BAUD ")) {
    // The host raises the link once the handshake proves the board is alive.
    // Boot stays at 115200 so the initial contact can never be the thing that
    // fails, and the host verifies the new rate with a PING before trusting
    // it — an unreliable bridge falls back instead of corrupting a transfer.
    uint32_t rate = (uint32_t) strtoul(line.substring(5).c_str(), nullptr, 10);
    if (rate < 9600) { Serial.println("ERR bad-baud"); return; }
    Serial.println("OK");
    Serial.flush();          // let "OK" leave at the old rate before switching
    delay(50);
    Serial.updateBaudRate(rate);
  } else if (line == "END") {
    Serial.println("BYE");
  }
}
`
}
