// Generates the ESP32 "provisioner" sketch — a tiny firmware flashed *before*
// the player so FastLED Studio can load songs (/music) and shows (/shows) onto
// the SD card over USB serial, then flash the player on top.
//
// ── Wire protocol (host → device) ─────────────────────────────────────────────
// Newline-terminated ASCII control lines, with raw binary payloads in between.
// The device drives flow control by ACKing each chunk, so the host never
// overruns the serial RX buffer while the SD write (slower than USB CDC) catches
// up:
//
//   boot            device prints "READY" once the SD card mounts (else "ERR …")
//   PING            device replies "READY" (re-probe — the boot "READY" may have
//                   been missed if the host opened the port after reset)
//   PUT <path> <n>  open <path> for writing (creating its parent dir); device
//                   replies "OK", then the host streams <n> bytes in blocks of at
//                   most PROVISION_CHUNK, the device replying "A" after each block
//                   is written, and "DONE" once all <n> bytes are stored.
//   END             device replies "BYE"; provisioning is complete.
//
// The Python helper (backend/) implements the host side; keep the two in sync.

export interface ProvisionerConfig {
  /** SD card chip-select pin (from the SDCard node). */
  sdCsPin: number
}

// GPIO10 avoids colliding with MatrixOutput's default LED data pin (GPIO5).
const DEFAULTS: ProvisionerConfig = { sdCsPin: 10 }

/** Transfer block size, in bytes — must match the host sender in the backend. */
export const PROVISION_CHUNK = 1024

export function generateProvisionerSketch(cfg: Partial<ProvisionerConfig> = {}): string {
  const c = { ...DEFAULTS, ...cfg }
  return `// FastLED Studio — SD Provisioner
// Receives files over USB serial and writes them to the SD card, so the studio
// can load /music and /shows before the player sketch is flashed. Generated by
// FastLED Studio — see provisionerSketchGenerator.ts for the wire protocol.

#include <SD.h>
#include <SPI.h>

#define SD_CS  ${c.sdCsPin}
#define CHUNK  ${PROVISION_CHUNK}

// Create the parent directory of \`path\` (one level is enough for /music, /shows).
void ensureDir(const String& path) {
  int slash = path.lastIndexOf('/');
  if (slash <= 0) return;
  String dir = path.substring(0, slash);
  if (dir.length() && !SD.exists(dir)) SD.mkdir(dir);
}

// Read one '\\n'-terminated control line, ignoring '\\r'.
String readLine() {
  String s;
  for (;;) {
    while (!Serial.available()) { /* wait */ }
    char ch = Serial.read();
    if (ch == '\\n') break;
    if (ch != '\\r') s += ch;
  }
  return s;
}

void setup() {
  Serial.begin(115200);
  while (!Serial) { /* wait for USB CDC */ }
  delay(200);
  if (!SD.begin(SD_CS)) { Serial.println("ERR sd-mount-failed"); for (;;) {} }
  Serial.println("READY");
}

void loop() {
  String line = readLine();
  if (line == "PING") {
    Serial.println("READY");
  } else if (line.startsWith("PUT ")) {
    int sp = line.indexOf(' ', 4);
    if (sp < 0) { Serial.println("ERR bad-put"); return; }
    String path = line.substring(4, sp);
    uint32_t size = (uint32_t) strtoul(line.substring(sp + 1).c_str(), nullptr, 10);

    ensureDir(path);
    if (SD.exists(path)) SD.remove(path);
    File f = SD.open(path, FILE_WRITE);
    if (!f) { Serial.println("ERR open-failed"); return; }
    Serial.println("OK");

    uint8_t buf[CHUNK];
    uint32_t remaining = size;
    while (remaining > 0) {
      uint32_t want = remaining < CHUNK ? remaining : CHUNK;
      uint32_t got = 0;
      while (got < want) {
        while (!Serial.available()) { /* wait */ }
        got += Serial.readBytes(buf + got, want - got);
      }
      f.write(buf, want);
      remaining -= want;
      Serial.println("A");   // ack: block written, send the next
    }
    f.close();
    Serial.println("DONE");
  } else if (line == "END") {
    Serial.println("BYE");
  }
}
`
}
