// Real-time clock support for generated sketches: the software clock and the
// DS3231 driver.

/*
 * Both RTC structs, ahead of the hoisted prototypes.
 *
 * The .ino preprocessor hoists a prototype for every function above all
 * user type definitions, so a function taking either struct by reference
 * needs it forward-declared here. `_RtcDateTimeValue` joined the list when
 * the bound clock helpers were retyped onto the value a graph wire carries.
 */
export const RTC_CPP_FORWARD = 'struct _RtcDateTime;\nstruct _RtcDateTimeValue;'

export function rtcHelperCpp(): string[] {
  return [
    '// ── RTC software clock helpers ────────────────────────────────────────────',
    'struct _RtcDateTime {',
    '  int16_t year;',
    '  uint8_t month, day, hour, minute, second, weekday;',
    '  bool valid;',
    '};',
    'struct _RtcDateTimeValue {',
    '  bool valid, synced, stale;',
    '  float hour, minute, second, weekday, day, month, year, secondsOfDay;',
    '  bool weekend;',
    '};',
    '',
    'bool _rtcLeap(int16_t year) {',
    '  return (year % 4 == 0) && ((year % 100 != 0) || (year % 400 == 0));',
    '}',
    '',
    'uint8_t _rtcDaysInMonth(int16_t year, uint8_t month) {',
    '  switch (month) {',
    '    case 2: return _rtcLeap(year) ? 29 : 28;',
    '    case 4: case 6: case 9: case 11: return 30;',
    '    default: return 31;',
    '  }',
    '}',
    '',
    'bool _rtcValidDateTime(int16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second) {',
    '  if (year < 1970 || year > 9999) return false;',
    '  if (month < 1 || month > 12) return false;',
    '  if (day < 1 || day > _rtcDaysInMonth(year, month)) return false;',
    '  if (hour > 23 || minute > 59 || second > 59) return false;',
    '  return true;',
    '}',
    '',
    'int32_t _rtcDaysFromCivil(int16_t year, uint8_t month, uint8_t day) {',
    '  year -= month <= 2;',
    '  const int32_t era = (year >= 0 ? year : year - 399) / 400;',
    '  const uint32_t yoe = (uint32_t)(year - era * 400);',
    '  const uint32_t shiftedMonth = (uint32_t)(month > 2 ? month - 3 : month + 9);',
    '  const uint32_t doy = (153u * shiftedMonth + 2u) / 5u + day - 1u;',
    '  const uint32_t doe = yoe * 365u + yoe / 4u - yoe / 100u + doy;',
    '  return era * 146097 + (int32_t)doe - 719468;',
    '}',
    '',
    'void _rtcCivilFromDays(int32_t z, int16_t &year, uint8_t &month, uint8_t &day) {',
    '  z += 719468;',
    '  const int32_t era = (z >= 0 ? z : z - 146096) / 146097;',
    '  const uint32_t doe = (uint32_t)(z - era * 146097);',
    '  const uint32_t yoe = (doe - doe / 1460u + doe / 36524u - doe / 146096u) / 365u;',
    '  year = (int16_t)(yoe + era * 400);',
    '  const uint32_t doy = doe - (365u * yoe + yoe / 4u - yoe / 100u);',
    '  const uint32_t mp = (5u * doy + 2u) / 153u;',
    '  day = (uint8_t)(doy - (153u * mp + 2u) / 5u + 1u);',
    '  month = (uint8_t)(mp < 10u ? mp + 3u : mp - 9u);',
    '  year += month <= 2;',
    '}',
    '',
    'uint8_t _rtcWeekdayFromDays(int32_t days) {',
    '  int32_t weekday = (days + 4) % 7;',
    '  if (weekday < 0) weekday += 7;',
    '  return (uint8_t)weekday;',
    '}',
    '',
    'uint8_t _rtcMonthFromBuildDate(const char *dateStr) {',
    "  switch (dateStr[0]) {",
    "    case 'J': return dateStr[1] == 'a' ? 1 : (dateStr[2] == 'n' ? 6 : 7);",
    "    case 'F': return 2;",
    "    case 'M': return dateStr[2] == 'r' ? 3 : 5;",
    "    case 'A': return dateStr[1] == 'p' ? 4 : 8;",
    "    case 'S': return 9;",
    "    case 'O': return 10;",
    "    case 'N': return 11;",
    "    case 'D': return 12;",
    "    default: return 0;",
    '  }',
    '}',
    '',
    '// One clock, formatted one way. A widget bound to the time and a fixed',
    '// Clock screen beside it must not disagree about what the hour looks like.',
    '// Takes the value a graph wire carries, not the parse helper\'s own struct:',
    '// they hold the same reading in different field types, and only this one',
    '// is what a panel is actually handed.',
    'const char *_rtcClockText(const _RtcDateTimeValue &dt) {',
    '  static char text[16];',
    '  if (!dt.valid) { snprintf(text, sizeof(text), "--:--:--"); return text; }',
    '  snprintf(text, sizeof(text), "%02d:%02d:%02d", (int)dt.hour, (int)dt.minute, (int)dt.second);',
    '  return text;',
    '}',
    '',
    'const char *_rtcDateText(const _RtcDateTimeValue &dt) {',
    '  static char text[16];',
    '  if (!dt.valid) { text[0] = 0; return text; }',
    '  snprintf(text, sizeof(text), "%04d-%02d-%02d", (int)dt.year, (int)dt.month, (int)dt.day);',
    '  return text;',
    '}',
    '',
    'bool _rtcParseBuildStamp(const char *dateStr, const char *timeStr, _RtcDateTime &out) {',
    '  const uint8_t month = _rtcMonthFromBuildDate(dateStr);',
    "  const uint8_t day = (uint8_t)((dateStr[4] == ' ' ? 0 : (dateStr[4] - '0')) * 10 + (dateStr[5] - '0'));",
    "  const int16_t year = (int16_t)((dateStr[7] - '0') * 1000 + (dateStr[8] - '0') * 100 + (dateStr[9] - '0') * 10 + (dateStr[10] - '0'));",
    "  const uint8_t hour = (uint8_t)((timeStr[0] - '0') * 10 + (timeStr[1] - '0'));",
    "  const uint8_t minute = (uint8_t)((timeStr[3] - '0') * 10 + (timeStr[4] - '0'));",
    "  const uint8_t second = (uint8_t)((timeStr[6] - '0') * 10 + (timeStr[7] - '0'));",
    '  if (!_rtcValidDateTime(year, month, day, hour, minute, second)) { out.valid = false; return false; }',
    '  out.year = year;',
    '  out.month = month;',
    '  out.day = day;',
    '  out.hour = hour;',
    '  out.minute = minute;',
    '  out.second = second;',
    '  out.weekday = _rtcWeekdayFromDays(_rtcDaysFromCivil(year, month, day));',
    '  out.valid = true;',
    '  return true;',
    '}',
    '',
  ]
}

/** Minimal DS3231 reader built on Arduino Wire. Keeping the register decoder in
 * generated code avoids a third-party RTClib dependency and works with every
 * supported Arduino core's default I2C bus. */
export function ds3231HelperCpp(): string[] {
  return [
    '// ── DS3231 hardware clock (I2C address 0x68) ─────────────────────────────',
    'uint8_t _rtcBcdToDec(uint8_t value) {',
    '  return (uint8_t)((value >> 4) * 10u + (value & 0x0fu));',
    '}',
    'uint8_t _rtcDecToBcd(uint8_t value) {',
    '  return (uint8_t)(((value / 10u) << 4) | (value % 10u));',
    '}',
    '',
    'bool _rtcReadDs3231(_RtcDateTime &out, bool &oscillatorStopped) {',
    '  Wire.beginTransmission(0x68);',
    '  Wire.write((uint8_t)0x00);',
    '  if (Wire.endTransmission() != 0) return false;',
    '  if (Wire.requestFrom((uint8_t)0x68, (uint8_t)7) != 7) return false;',
    '  const uint8_t rawSecond = Wire.read();',
    '  const uint8_t rawMinute = Wire.read();',
    '  const uint8_t rawHour = Wire.read();',
    '  Wire.read();  // chip day-of-week; derive it from the validated date below',
    '  const uint8_t rawDay = Wire.read();',
    '  const uint8_t rawMonth = Wire.read();',
    '  const uint8_t rawYear = Wire.read();',
    '',
    '  uint8_t hour;',
    '  if (rawHour & 0x40u) {',
    '    hour = _rtcBcdToDec(rawHour & 0x1fu);',
    '    if (hour == 12u) hour = 0u;',
    '    if (rawHour & 0x20u) hour = (uint8_t)(hour + 12u);',
    '  } else {',
    '    hour = _rtcBcdToDec(rawHour & 0x3fu);',
    '  }',
    '  const uint8_t month = _rtcBcdToDec(rawMonth & 0x1fu);',
    '  const int16_t year = (int16_t)(2000 + _rtcBcdToDec(rawYear) + ((rawMonth & 0x80u) ? 100 : 0));',
    '  const uint8_t day = _rtcBcdToDec(rawDay & 0x3fu);',
    '  const uint8_t minute = _rtcBcdToDec(rawMinute & 0x7fu);',
    '  const uint8_t second = _rtcBcdToDec(rawSecond & 0x7fu);',
    '  if (!_rtcValidDateTime(year, month, day, hour, minute, second)) return false;',
    '',
    '  out.year = year; out.month = month; out.day = day;',
    '  out.hour = hour; out.minute = minute; out.second = second;',
    '  out.weekday = _rtcWeekdayFromDays(_rtcDaysFromCivil(year, month, day));',
    '  out.valid = true;',
    '',
    '  // OSF (status bit 7) means the oscillator stopped and the stored time may',
    '  // be wrong. A status-register read failure also leaves the sample stale.',
    '  oscillatorStopped = true;',
    '  Wire.beginTransmission(0x68);',
    '  Wire.write((uint8_t)0x0f);',
    '  if (Wire.endTransmission() == 0 && Wire.requestFrom((uint8_t)0x68, (uint8_t)1) == 1) {',
    '    oscillatorStopped = (Wire.read() & 0x80u) != 0;',
    '  }',
    '  return true;',
    '}',
    '',
    'bool _rtcWriteDs3231(int16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second) {',
    '  if (!_rtcValidDateTime(year, month, day, hour, minute, second) || year < 2000 || year > 2199) return false;',
    '  const uint8_t weekday = (uint8_t)(_rtcWeekdayFromDays(_rtcDaysFromCivil(year, month, day)) + 1u);',
    '  Wire.beginTransmission(0x68);',
    '  Wire.write((uint8_t)0x00);',
    '  Wire.write(_rtcDecToBcd(second)); Wire.write(_rtcDecToBcd(minute)); Wire.write(_rtcDecToBcd(hour));',
    '  Wire.write(_rtcDecToBcd(weekday)); Wire.write(_rtcDecToBcd(day));',
    '  Wire.write((uint8_t)(_rtcDecToBcd(month) | (year >= 2100 ? 0x80u : 0u)));',
    '  Wire.write(_rtcDecToBcd((uint8_t)(year % 100)));',
    '  if (Wire.endTransmission() != 0) return false;',
    '  // A deliberate successful set makes the reading trustworthy again.',
    '  Wire.beginTransmission(0x68); Wire.write((uint8_t)0x0f);',
    '  if (Wire.endTransmission() != 0 || Wire.requestFrom((uint8_t)0x68, (uint8_t)1) != 1) return false;',
    '  const uint8_t status = Wire.read();',
    '  Wire.beginTransmission(0x68); Wire.write((uint8_t)0x0f); Wire.write((uint8_t)(status & ~0x80u));',
    '  return Wire.endTransmission() == 0;',
    '}',
    '',
    'void _rtcHandleSerialSet() {',
    '  static char line[48]; static uint8_t length = 0;',
    '  while (Serial.available() > 0) {',
    '    const char ch = (char)Serial.read();',
    "    if (ch == '\\r') continue;",
    "    if (ch != '\\n') { if (length + 1 < sizeof(line)) line[length++] = ch; continue; }",
    "    line[length] = '\\0'; length = 0;",
    '    int year, month, day, hour, minute, second;',
    '    if (sscanf(line, "FLS_RTC_SET %d-%d-%d %d:%d:%d", &year, &month, &day, &hour, &minute, &second) == 6',
    '        && _rtcWriteDs3231((int16_t)year, (uint8_t)month, (uint8_t)day, (uint8_t)hour, (uint8_t)minute, (uint8_t)second)) {',
    '      Serial.println("RTC clock set successfully");',
    '      Serial.println("FLS_RTC_OK");',
    '    } else if (strncmp(line, "FLS_RTC_SET", 11) == 0) {',
    '      Serial.println("RTC clock set failed");',
    '      Serial.println("FLS_RTC_ERROR");',
    '    }',
    '  }',
    '}',
    '',
  ]
}
