/**
 * A sketch whose only job is to find which pins a board's onboard SD card is on.
 *
 * Some boards carry a microSD slot wired to pins nobody chose and nobody can
 * change. The family documentation usually names them, and it is usually
 * right — but "usually right" is exactly what HW-12 refused to record for the
 * ESP32-2432S028R, because a pin map copied from a forum post and a pin map
 * measured on the board in hand look identical in the source and only one of
 * them is evidence. So: try the candidates on the actual unit and report which
 * one mounts a card.
 *
 * Generated from a candidate list alone — no graph, no validation, no FastLED,
 * and nothing to wire. Like the touch calibration sketch it is *temporary*: the
 * board keeps running it until the project is uploaded again.
 *
 * It answers two questions, not one. Which pins the slot is on, and — because
 * the candidates say which SPI host each set belongs to — whether the card
 * shares a bus with the panel or sits on its own. That second answer is what
 * decides whether a shared-bus contention test is even possible on the board,
 * which is a question no amount of desk reasoning could settle.
 */

/** One wiring to try, in the order a caller wants them tried. */
export interface SdPinCandidate {
  /** Shown beside the result, e.g. "VSPI (family default)". */
  label: string
  csPin: number
  sckPin: number
  misoPin: number
  mosiPin: number
}

export interface SdPinProbeTarget {
  candidates: readonly SdPinCandidate[]
  /**
   * Pins to hold HIGH (deselected) for the whole probe.
   *
   * A candidate set may share SCK/MOSI/MISO with a display already soldered to
   * the same bus. Probing then clocks data past that panel, which is harmless
   * only while its chip select is high — so the caller names every other device
   * on the board and this holds them off. Leaving one out corrupts whatever
   * that device happens to be showing, and on a panel with no framebuffer the
   * mess stays on the glass.
   */
  deselectPins?: readonly number[]
  /** Seconds between repeats. The probe loops so a card can be inserted late. */
  retrySeconds?: number
}

/**
 * The ESP32-2432S028R's candidates, most likely first.
 *
 * Both are *proposals to test*, not recorded facts — which is the whole point
 * of the sketch. The first is the pinout the family documentation gives, on
 * the second SPI host; the second is the panel's own bus, which is the case
 * that would make a shared-bus test possible. `csPin` differs between them
 * because a shared bus needs a chip select of its own.
 */
export const CYD_SD_CANDIDATES: readonly SdPinCandidate[] = [
  { label: 'VSPI, separate from the panel (family default)', csPin: 5, sckPin: 18, misoPin: 19, mosiPin: 23 },
  { label: "HSPI, shared with the panel's own bus", csPin: 5, sckPin: 14, misoPin: 12, mosiPin: 13 },
]

/** The CYD's panel and digitiser chip selects, from `integratedBoardHardware.ts`. */
export const CYD_DESELECT_PINS: readonly number[] = [15, 33]

const MARKER = 'FLS_SD'

export function generateSdPinProbeSketch(target: SdPinProbeTarget): string {
  const { candidates } = target
  if (candidates.length === 0) throw new Error('an SD pin probe needs at least one candidate')
  const retryMs = Math.max(1, Math.round(target.retrySeconds ?? 5)) * 1000
  const deselect = target.deselectPins ?? []

  const table = candidates
    .map((c) => `  { ${c.csPin}, ${c.sckPin}, ${c.misoPin}, ${c.mosiPin}, ${JSON.stringify(c.label)} },`)
    .join('\n')

  return `// Generated by Design Studio for FastLED — onboard SD pin probe.
//
// Temporary bench instrument. It mounts nothing permanently and writes nothing
// to the card; it reports over serial at 115200 and repeats until reset.
// Upload your project again to remove it.
#include <SPI.h>
#include <SD.h>

struct SdCandidate { uint8_t cs, sck, miso, mosi; const char* label; };

static const SdCandidate CANDIDATES[] = {
${table}
};
static const size_t CANDIDATE_COUNT = sizeof(CANDIDATES) / sizeof(CANDIDATES[0]);
${deselect.length > 0 ? `static const uint8_t DESELECT[] = { ${deselect.join(', ')} };
static const size_t DESELECT_COUNT = sizeof(DESELECT) / sizeof(DESELECT[0]);` : ''}

// A separate bus object per attempt: SPI is the Arduino singleton the panel may
// already own, and re-begin()ing that underneath it is how you corrupt a
// display rather than probe a card.
static SPIClass probeBus(HSPI);

static const char* cardTypeName(uint8_t type) {
  switch (type) {
    case CARD_NONE:  return "none";
    case CARD_MMC:   return "MMC";
    case CARD_SD:    return "SDSC";
    case CARD_SDHC:  return "SDHC";
    default:         return "unknown";
  }
}

/*
 * One attempt, reported whether it works or not.
 *
 * A mount that returns true is not proof on its own — a floating MISO can look
 * like a reply — so this also asks for the card type and size and refuses to
 * call it a pass unless the card names itself and has a non-zero capacity.
 */
static bool tryCandidate(const SdCandidate& c) {
  Serial.printf("${MARKER} trying cs=%u sck=%u miso=%u mosi=%u  (%s)\n",
                c.cs, c.sck, c.miso, c.mosi, c.label);
  pinMode(c.cs, OUTPUT);
  digitalWrite(c.cs, HIGH);
  probeBus.begin(c.sck, c.miso, c.mosi, c.cs);
  bool mounted = SD.begin(c.cs, probeBus);
  if (!mounted) {
    Serial.printf("${MARKER}   no card mounted on these pins\n");
    SD.end();
    probeBus.end();
    return false;
  }
  uint8_t type = SD.cardType();
  uint64_t bytes = SD.cardSize();
  if (type == CARD_NONE || bytes == 0) {
    Serial.printf("${MARKER}   mounted but the card does not answer — treating as a miss\n");
    SD.end();
    probeBus.end();
    return false;
  }
  Serial.printf("${MARKER} FOUND cs=%u sck=%u miso=%u mosi=%u type=%s size=%lluMB  (%s)\n",
                c.cs, c.sck, c.miso, c.mosi, cardTypeName(type),
                (unsigned long long)(bytes / (1024ULL * 1024ULL)), c.label);
  File root = SD.open("/");
  if (root) {
    Serial.printf("${MARKER}   root listing:\n");
    for (File entry = root.openNextFile(); entry; entry = root.openNextFile()) {
      Serial.printf("${MARKER}     %s%s  %lu\n", entry.name(),
                    entry.isDirectory() ? "/" : "", (unsigned long)entry.size());
    }
    root.close();
  }
  SD.end();
  probeBus.end();
  return true;
}

void setup() {
  Serial.begin(115200);
  delay(300);
  Serial.printf("\n${MARKER} onboard SD pin probe — %u candidate(s)\n", (unsigned)CANDIDATE_COUNT);
${deselect.length > 0 ? `  // Hold every other device on the board off the bus before clocking it.
  for (size_t i = 0; i < DESELECT_COUNT; i++) { pinMode(DESELECT[i], OUTPUT); digitalWrite(DESELECT[i], HIGH); }
  Serial.printf("${MARKER} holding %u other chip select(s) high\n", (unsigned)DESELECT_COUNT);` : ''}
}

void loop() {
  bool found = false;
  for (size_t i = 0; i < CANDIDATE_COUNT && !found; i++) found = tryCandidate(CANDIDATES[i]);
  if (!found) {
    Serial.printf("${MARKER} no candidate mounted a card.\n");
    Serial.printf("${MARKER} Check a card is inserted and formatted FAT32, then wait for the retry.\n");
  }
  Serial.printf("${MARKER} retrying in ${Math.round(retryMs / 1000)}s\n\n");
  delay(${retryMs});
}
`
}
