/**
 * A sketch whose only job is to report where a finger landed.
 *
 * Calibration used to ride the project's own sketch with the Board's telemetry
 * switch thrown, which asked far too much for a measurement the app should
 * just take. Three things had to be true at once — telemetry on, a layout or a
 * wired Controls output that made the generator sample touch at all, and a
 * graph that passes deploy validation — and a panel being calibrated usually
 * has none of them. A screen-only graph is refused outright for having no LED
 * output, so the very graphs that most need calibrating were the ones that
 * could not be uploaded at all.
 *
 * So this is generated from the panel alone: no graph, no validation, no
 * FastLED, and no telemetry property to set. It paints four numbered corner
 * targets matching the wizard's own corner map, and prints one raw reading per
 * interval while the glass is held. Nothing else.
 *
 * It is a *temporary* sketch, and the wizard says so when it finishes: the
 * board keeps running this until the project is uploaded again.
 */

import {
  TFT_CONTROLLERS,
  TFT_LETTER_SPACING,
  tftMadctl,
  tftRotatedSize,
  tftWindowOrigin,
  type TftController,
  type TftRotation,
} from '../state/tftSurface'
import { TELEMETRY_TOUCH_INTERVAL_MS } from '../state/deviceTelemetry'
import { FONT_W, FONT_H } from '../state/font'
import { telemetryTouchSampleCpp } from './deviceTelemetryCpp'
import {
  TFT_DISPLAY_CPP_FORWARD,
  TFT_DISPLAY_CPP_INCLUDES,
  tftDisplayHelpersCpp,
} from './tftDisplayCpp'
import { TFT_TOUCH_CPP_HELPERS, tftTouchIrqSetupCpp } from './tftTouchCpp'

/** Everything the sketch needs, resolved from the panel. */
export interface TouchCalibrationSketchTarget {
  controller: TftController
  rotation: TftRotation
  csPin: number
  dcPin: number
  resetPin: number
  sckPin: number
  mosiPin: number
  backlightPin: number
  touchCsPin: number
  touchIrqPin: number
  touchSckPin: number
  touchMosiPin: number
  touchMisoPin: number
}

/** Corner marker size in native pixels: big enough to hit with a fingertip,
 *  small enough that its centre is near the extreme being measured. */
const TARGET = 28

/** Half-width of the dot left where a press landed. */
const MARK = 2

/**
 * Text metrics, from the same constants the emitted `_tftTextWidth` uses.
 *
 * The 3x5 font at scale 1 is five pixels tall on a panel 320 pixels high —
 * legible in a screenshot and not at arm's length, which is where this is
 * read from. So the instruction is sized to the glass rather than left at the
 * default the fixed layouts use for fields that must fit a stranger's title.
 */
function textWidth(text: string, scale: number): number {
  return text.length === 0 ? 0 : ((text.length * (FONT_W + TFT_LETTER_SPACING)) - TFT_LETTER_SPACING) * scale
}

/** The largest whole scale at which `text` still fits `width`, within reason. */
function fittingScale(text: string, width: number, max = 4): number {
  for (let scale = max; scale > 1; scale -= 1) {
    if (textWidth(text, scale) <= width - 16) return scale
  }
  return 1
}

/**
 * Raw bounds this sketch maps with — the full ADC range, deliberately.
 *
 * It reports `rawX`/`rawY` and never uses the mapped pixel, so feeding the
 * panel's stored calibration in here would make the measurement depend on the
 * value being measured.
 */
const RAW_MIN = 0
const RAW_MAX = 4095

const ROTATION_CODE: Record<TftRotation, number> = { 0: 0, 90: 1, 180: 2, 270: 3 }

export function generateTouchCalibrationSketch(target: TouchCalibrationSketchTarget): string {
  const size = tftRotatedSize(target.controller, target.rotation)
  const origin = tftWindowOrigin(target.controller, target.rotation)
  const madctl = tftMadctl(target.controller, target.rotation)
  const right = size.width - TARGET
  const bottom = size.height - TARGET
  // Same order as TOUCH_CALIBRATION_CORNERS, so the number on the glass is the
  // number the wizard is asking for.
  const corners: [number, number, string][] = [
    [0, 0, '1'],
    [right, 0, '2'],
    [right, bottom, '3'],
    [0, bottom, '4'],
  ]
  const middle = Math.round(size.height / 2)
  const lines = ['TOUCH THE', 'NUMBERED BOX']
  // One scale for both lines, chosen from the wider: two sizes in one message
  // reads as emphasis nobody meant.
  const messageScale = Math.min(...lines.map((line) => fittingScale(line, size.width)))
  const lineHeight = (FONT_H + 2) * messageScale
  // A digit is one glyph, centred in its own box — the box centre is the point
  // the calibration wants pressed, so the label and the target are the same
  // thing rather than two marks to choose between.
  const digitScale = Math.max(1, Math.min(3, Math.floor((TARGET - 8) / FONT_H)))
  const digitX = Math.round((TARGET - textWidth('1', digitScale)) / 2)
  const digitY = Math.round((TARGET - FONT_H * digitScale) / 2)

  return [
    '// Touch calibration — generated by Design Studio for FastLED.',
    '//',
    '// A temporary measuring sketch, not your project. Upload the project again',
    '// once calibration is saved.',
    TFT_DISPLAY_CPP_INCLUDES,
    '',
    TFT_DISPLAY_CPP_FORWARD,
    '',
    tftDisplayHelpersCpp(),
    TFT_TOUCH_CPP_HELPERS,
    '',
    'static TftPanel _calPanel;',
    'static uint32_t _calSampleMs = 0;',
    '',
    // Defined above its caller rather than relying on the .ino preprocessor's
    // hoisted prototypes. It takes nothing by reference, so it could sit
    // anywhere (see displayForwardDeclarations.test.ts) — this just spares the
    // question of whether `static` functions get a prototype at all.
    'static void _calBegin() {',
    `  _tftBegin(_calPanel, ${target.csPin}, ${target.dcPin}, ${target.resetPin}, `
      + `${target.sckPin}, ${target.mosiPin}, ${target.backlightPin}, `
      + `${size.width}, ${size.height}, ${origin.col}, ${origin.row}, `
      + `0x${madctl.toString(16).padStart(2, '0')}, ${target.controller.invert}, TFT_C_BG);`,
    '  _tftBacklight(_calPanel, true);',
    ...corners.flatMap(([x, y, label]) => [
      `  _tftRect(_calPanel, ${x}, ${y}, ${TARGET}, ${TARGET}, TFT_C_ACCENT);`,
      `  _tftText(_calPanel, ${x + digitX}, ${y + digitY}, "${label}", TFT_C_TEXT, ${digitScale});`,
    ]),
    ...lines.map((line, index) => {
      const y = middle - Math.round((lines.length * lineHeight) / 2) + index * lineHeight
      return `  _tftText(_calPanel, ${Math.round((size.width - textWidth(line, messageScale)) / 2)}, `
        + `${y}, "${line}", TFT_C_DIM, ${messageScale});`
    }),
    '}',
    '',
    'void setup() {',
    '  Serial.begin(115200);',
    '  _calBegin();',
    `  pinMode(${target.touchCsPin}, OUTPUT); digitalWrite(${target.touchCsPin}, HIGH);`,
    `  pinMode(${target.touchSckPin}, OUTPUT); digitalWrite(${target.touchSckPin}, LOW);`,
    `  pinMode(${target.touchMosiPin}, OUTPUT); pinMode(${target.touchMisoPin}, INPUT);`,
    ...tftTouchIrqSetupCpp(target.touchIrqPin),
    '}',
    '',
    'void loop() {',
    '  int16_t x = 0, y = 0;',
    '  uint16_t rawX = 0, rawY = 0;',
    `  bool pressed = _xptPoint(${target.touchCsPin}, ${target.touchIrqPin}, ${target.touchSckPin}, `
      + `${target.touchMosiPin}, ${target.touchMisoPin}, ${RAW_MIN}, ${RAW_MAX}, ${RAW_MIN}, ${RAW_MAX}, `
      + `${target.controller.width}, ${target.controller.height}, ${ROTATION_CODE[target.rotation]}, `
      + 'x, y, rawX, rawY);',
    '  if (pressed) {',
    '    uint32_t now = millis();',
    `    if (_calSampleMs == 0 || (uint32_t)(now - _calSampleMs) >= ${TELEMETRY_TOUCH_INTERVAL_MS}u) {`,
    `      ${telemetryTouchSampleCpp('rawX', 'rawY')}`,
    /*
     * A mark where the press landed, so the glass answers as well as the
     * wizard — a panel that draws nothing is indistinguishable from a
     * digitiser nobody wired.
     *
     * Inside the sample interval rather than every pass, so a held finger
     * costs one small blit per reading instead of one every eight
     * milliseconds down a bit-banged bus. Marks accumulate: erasing one would
     * take the corner box underneath it too, and four presses leaving four
     * dots is the more useful picture anyway.
     *
     * Drawn at the *uncalibrated* position, which is the point rather than a
     * shortcoming — a dot on the opposite side to the finger is this panel's
     * reversed axis, made visible.
     */
    `      _tftFillRect(_calPanel, constrain(x - ${MARK}, 0, ${size.width - MARK * 2 - 1}), `
      + `constrain(y - ${MARK}, 0, ${size.height - MARK * 2 - 1}), `
      + `${MARK * 2 + 1}, ${MARK * 2 + 1}, TFT_C_ON);`,
    '      _calSampleMs = now;',
    '    }',
    '  } else {',
    '    _calSampleMs = 0;',
    '  }',
    '  delay(8);',
    '}',
    '',
  ].join('\n')
}

/** Resolve the sketch target from a panel node's own properties. */
export function touchCalibrationTargetFor(
  panelProperties: Record<string, unknown>,
  controller: TftController | null,
  rotation: TftRotation,
): TouchCalibrationSketchTarget {
  const pin = (key: string, fallback: number) => {
    const value = Math.round(Number(panelProperties[key]))
    return Number.isFinite(value) && value >= 0 && value <= 255 ? value : fallback
  }
  return {
    controller: controller ?? TFT_CONTROLLERS.ST7789,
    rotation,
    csPin: pin('csPin', 5),
    dcPin: pin('dcPin', 16),
    resetPin: pin('resetPin', 17),
    sckPin: pin('sckPin', 18),
    mosiPin: pin('mosiPin', 23),
    backlightPin: pin('backlightPin', 4),
    touchCsPin: pin('touchCsPin', 15),
    touchIrqPin: pin('touchIrqPin', 2),
    touchSckPin: pin('touchSckPin', 18),
    touchMosiPin: pin('touchMosiPin', 23),
    touchMisoPin: pin('touchMisoPin', 19),
  }
}
