import type { StudioNode } from '../state/graphStore'
import { buildXYTable } from '../state/xyLayout'
import { ledHardwareFromProps, fastledSetupCpp, overclockDefineCpp } from './cppGenerator'
import { SPI_CHIPSETS } from '../state/nodeLibrary'

function intProp(val: unknown, def: number, min: number, max: number): number {
  const n = Math.round(Number(val))
  return Number.isFinite(n) ? Math.max(min, Math.min(max, n)) : def
}

function matrixOutputNode(nodes: StudioNode[], outputNodeId?: string): StudioNode | undefined {
  return nodes.find((node) => node.id === outputNodeId && node.data.nodeType === 'MatrixOutput')
    ?? nodes.find((n) => n.data.nodeType === 'MatrixOutput')
}

/** Generate a standalone hardware-wiring diagnostic sketch from the current
 *  MatrixOutput settings. The sketch cycles through color-order solids,
 *  brightness/current-limit bars, an orientation gradient, panel numbering,
 *  a logical XY chase, and a direct physical-index chase, so it can be flashed
 *  before the user has built a normal creative graph. */
export function generateWiringDiagnosticSketch(nodes: StudioNode[], outputNodeId?: string): string | null {
  const outputNode = matrixOutputNode(nodes, outputNodeId)
  if (!outputNode) return null

  const p = outputNode.data.properties as Record<string, unknown>
  const width = intProp(p.width, 16, 1, 64)
  const height = intProp(p.height, 16, 1, 64)
  const dataPin = intProp(p.dataPin, 5, 0, 48)
  const hw = ledHardwareFromProps(p)
  const xyTable = buildXYTable(width, height, p)
  const powerLimit = p.powerLimit === true
  const volts = intProp(p.volts, 5, 1, 24)
  const milliamps = intProp(p.milliamps, 2000, 100, 50000)
  const layout = p.layout === 'panels' ? 'panels' : 'matrix'
  const tilesX = layout === 'panels' ? intProp(p.tilesX, 1, 1, 8) : 1
  const tilesY = layout === 'panels' ? intProp(p.tilesY, 1, 1, 8) : 1
  const panelsValid = layout === 'panels' && width % tilesX === 0 && height % tilesY === 0
  const effectiveTilesX = panelsValid ? tilesX : 1
  const effectiveTilesY = panelsValid ? tilesY : 1
  const tileW = Math.max(1, Math.floor(width / effectiveTilesX))
  const tileH = Math.max(1, Math.floor(height / effectiveTilesY))
  const modeMs = 3200
  const chaseMs = 90

  const lines: string[] = []
  lines.push('// Design Studio for FastLED — Matrix Output wiring diagnostic.')
  lines.push('// Flash this when you want to verify hardware before loading a creative graph.')
  lines.push('// The sketch cycles through: RGB color-order solids, brightness/current-limit')
  lines.push('// bars, an orientation gradient, panel numbering, a logical XY chase, and a')
  lines.push('// direct physical-index chase for dead-pixel / chain-order checks.')
  lines.push(...overclockDefineCpp(hw))
  lines.push('#include <FastLED.h>')
  lines.push('#include <stdio.h>')
  lines.push('')
  lines.push(`#define DATA_PIN ${dataPin}`)
  if (SPI_CHIPSETS.has(hw.chipset)) lines.push(`#define CLOCK_PIN ${hw.clockPin}`)
  lines.push(`#define WIDTH ${width}`)
  lines.push(`#define HEIGHT ${height}`)
  lines.push('#define NUM_LEDS (WIDTH * HEIGHT)')
  lines.push(`#define PANEL_TILES_X ${effectiveTilesX}`)
  lines.push(`#define PANEL_TILES_Y ${effectiveTilesY}`)
  lines.push(`#define PANEL_W ${tileW}`)
  lines.push(`#define PANEL_H ${tileH}`)
  lines.push(`#define DIAG_MODE_MS ${modeMs}`)
  lines.push(`#define DIAG_CHASE_MS ${chaseMs}`)
  lines.push('')
  lines.push('CRGB leds[NUM_LEDS];')
  lines.push('')
  if (xyTable) {
    lines.push('// Physical wiring map (grid index -> physical LED index), baked from')
    lines.push("// MatrixOutput's serpentine / panel / custom-layout settings.")
    lines.push(`const uint16_t _xytable[${width * height}] PROGMEM = { ${xyTable.join(',')} };`)
    lines.push(`uint16_t XY(uint8_t x, uint8_t y) { return pgm_read_word(&_xytable[(uint16_t)y * WIDTH + x]); }`)
    lines.push('')
  }
  lines.push('const uint8_t DIGITS[10][5] PROGMEM = {')
  lines.push('  { 0b111, 0b101, 0b101, 0b101, 0b111 },')
  lines.push('  { 0b010, 0b110, 0b010, 0b010, 0b111 },')
  lines.push('  { 0b111, 0b001, 0b111, 0b100, 0b111 },')
  lines.push('  { 0b111, 0b001, 0b111, 0b001, 0b111 },')
  lines.push('  { 0b101, 0b101, 0b111, 0b001, 0b001 },')
  lines.push('  { 0b111, 0b100, 0b111, 0b001, 0b111 },')
  lines.push('  { 0b111, 0b100, 0b111, 0b101, 0b111 },')
  lines.push('  { 0b111, 0b001, 0b001, 0b001, 0b001 },')
  lines.push('  { 0b111, 0b101, 0b111, 0b101, 0b111 },')
  lines.push('  { 0b111, 0b101, 0b111, 0b001, 0b111 }')
  lines.push('};')
  lines.push('')
  lines.push('void plot(int x, int y, const CRGB& color) {')
  lines.push('  if (x < 0 || x >= WIDTH || y < 0 || y >= HEIGHT) return;')
  if (xyTable) lines.push('  leds[XY((uint8_t)x, (uint8_t)y)] = color;')
  else lines.push('  leds[(uint16_t)y * WIDTH + x] = color;')
  lines.push('}')
  lines.push('')
  lines.push('void drawDigit(int x, int y, int digit, const CRGB& color) {')
  lines.push('  if (digit < 0 || digit > 9) return;')
  lines.push('  for (int row = 0; row < 5; row++) {')
  lines.push('    uint8_t bits = pgm_read_byte(&DIGITS[digit][row]);')
  lines.push('    for (int col = 0; col < 3; col++) {')
  lines.push('      if (bits & (1 << (2 - col))) plot(x + col, y + row, color);')
  lines.push('    }')
  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('void drawNumber(int x, int y, int value, const CRGB& color) {')
  lines.push('  char buf[8];')
  lines.push('  if (value < 0) value = 0;')
  lines.push('  snprintf(buf, sizeof(buf), "%d", value);')
  lines.push('  for (int i = 0; buf[i] && i < 7; i++) {')
  lines.push('    int digit = buf[i] - \'0\';')
  lines.push('    if (digit >= 0 && digit <= 9) drawDigit(x + i * 4, y, digit, color);')
  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('void drawBrightnessBars() {')
  lines.push('  static const uint8_t levels[5] = { 16, 48, 96, 160, 255 };')
  lines.push('  for (int y = 0; y < HEIGHT; y++) for (int x = 0; x < WIDTH; x++) {')
  lines.push('    int band = (x * 5) / WIDTH; if (band > 4) band = 4;')
  lines.push('    uint8_t v = levels[band];')
  lines.push('    plot(x, y, CRGB(v, v, v));')
  lines.push('  }')
  lines.push('  if (HEIGHT >= 6) {')
  lines.push('    int labelY = HEIGHT - 5;')
  lines.push('    for (int band = 0; band < 5; band++) {')
  lines.push('      int startX = (band * WIDTH) / 5;')
  lines.push('      int endX = ((band + 1) * WIDTH) / 5 - 1;')
  lines.push('      int labelX = startX + ((endX - startX + 1) - 3) / 2;')
  lines.push('      drawDigit(labelX, labelY, band + 1, levels[band] >= 128 ? CRGB::Black : CRGB::White);')
  lines.push('    }')
  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('void drawOrientationMap(bool blink) {')
  lines.push('  for (int y = 0; y < HEIGHT; y++) for (int x = 0; x < WIDTH; x++) {')
  lines.push('    uint8_t r = WIDTH > 1 ? (uint8_t)((x * 255) / (WIDTH - 1)) : 255;')
  lines.push('    uint8_t b = HEIGHT > 1 ? (uint8_t)((y * 255) / (HEIGHT - 1)) : 255;')
  lines.push('    plot(x, y, CRGB(r, 20, b));')
  lines.push('  }')
  lines.push('  plot(0, 0, blink ? CRGB::White : CRGB(40, 40, 40));')
  lines.push('  if (WIDTH > 1) plot(WIDTH - 1, 0, CRGB::Red);')
  lines.push('  if (HEIGHT > 1) plot(0, HEIGHT - 1, CRGB::Blue);')
  lines.push('  if (WIDTH > 1 && HEIGHT > 1) plot(WIDTH - 1, HEIGHT - 1, CRGB::Green);')
  lines.push('  if (WIDTH > 2) plot(1, 0, CRGB::White);')
  lines.push('  if (HEIGHT > 2) plot(0, 1, CRGB::White);')
  lines.push('}')
  lines.push('')
  lines.push('void drawPanelDiagnostic() {')
  lines.push('  fill_solid(leds, NUM_LEDS, CRGB::Black);')
  lines.push('  for (int ty = 0; ty < PANEL_TILES_Y; ty++) for (int tx = 0; tx < PANEL_TILES_X; tx++) {')
  lines.push('    int panelIndex = ty * PANEL_TILES_X + tx;')
  lines.push('    int px = tx * PANEL_W;')
  lines.push('    int py = ty * PANEL_H;')
  lines.push('    CHSV fill = CHSV((uint8_t)(panelIndex * 37), 210, 28);')
  lines.push('    CHSV edge = CHSV((uint8_t)(panelIndex * 37), 255, 120);')
  lines.push('    for (int y = 0; y < PANEL_H; y++) for (int x = 0; x < PANEL_W; x++) plot(px + x, py + y, fill);')
  lines.push('    for (int x = 0; x < PANEL_W; x++) { plot(px + x, py, edge); plot(px + x, py + PANEL_H - 1, edge); }')
  lines.push('    for (int y = 0; y < PANEL_H; y++) { plot(px, py + y, edge); plot(px + PANEL_W - 1, py + y, edge); }')
  lines.push('    int notchW = PANEL_W > 3 ? 2 : 1;')
  lines.push('    int notchH = PANEL_H > 3 ? 2 : 1;')
  lines.push('    for (int ny = 0; ny < notchH; ny++) for (int nx = 0; nx < notchW; nx++) plot(px + nx, py + ny, CRGB::White);')
  lines.push('    if (PANEL_W >= 3 && PANEL_H >= 5) {')
  lines.push('      char label[4];')
  lines.push('      snprintf(label, sizeof(label), "%d", panelIndex);')
  lines.push('      int digits = (label[1] == \'\\0\') ? 1 : (label[2] == \'\\0\') ? 2 : 3;')
  lines.push('      int labelW = digits * 4 - 1;')
  lines.push('      int labelX = px + (PANEL_W - labelW) / 2;')
  lines.push('      int labelY = py + (PANEL_H - 5) / 2;')
  lines.push('      drawNumber(labelX, labelY, panelIndex, CRGB::White);')
  lines.push('    }')
  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('void drawLogicalChase(uint32_t now) {')
  lines.push('  fill_solid(leds, NUM_LEDS, CRGB::Black);')
  lines.push('  int logical = (int)((now / DIAG_CHASE_MS) % NUM_LEDS);')
  lines.push('  int x = logical % WIDTH;')
  lines.push('  int y = logical / WIDTH;')
  lines.push('  plot(x, y, CHSV((uint8_t)(logical * 11), 255, 255));')
  lines.push('  drawNumber(0, 0, logical, CRGB::White);')
  lines.push('}')
  lines.push('')
  lines.push('void drawPhysicalChase(uint32_t now) {')
  lines.push('  fill_solid(leds, NUM_LEDS, CRGB::Black);')
  lines.push('  int physical = (int)((now / DIAG_CHASE_MS) % NUM_LEDS);')
  lines.push('  leds[physical] = CHSV((uint8_t)(physical * 13), 255, 255);')
  lines.push('  if (NUM_LEDS > 1) leds[(physical + NUM_LEDS - 1) % NUM_LEDS] = CHSV((uint8_t)(physical * 13), 255, 72);')
  lines.push('  drawNumber(0, 0, physical, CRGB::White);')
  lines.push('}')
  lines.push('')
  lines.push('void setup() {')
  lines.push(...fastledSetupCpp(hw))
  if (powerLimit) lines.push(`  FastLED.setMaxPowerInVoltsAndMilliamps(${volts}, ${milliamps});`)
  lines.push('}')
  lines.push('')
  lines.push('void loop() {')
  lines.push('  uint32_t now = millis();')
  lines.push('  uint8_t mode = (uint8_t)((now / DIAG_MODE_MS) % 8);')
  lines.push('  bool blink = ((now / 240) & 1) == 0;')
  lines.push('  switch (mode) {')
  lines.push('    case 0: fill_solid(leds, NUM_LEDS, CRGB::Red); break;')
  lines.push('    case 1: fill_solid(leds, NUM_LEDS, CRGB::Green); break;')
  lines.push('    case 2: fill_solid(leds, NUM_LEDS, CRGB::Blue); break;')
  lines.push('    case 3: drawBrightnessBars(); break;')
  lines.push('    case 4: drawOrientationMap(blink); break;')
  lines.push('    case 5: drawPanelDiagnostic(); break;')
  lines.push('    case 6: drawLogicalChase(now); break;')
  lines.push('    default: drawPhysicalChase(now); break;')
  lines.push('  }')
  lines.push('  FastLED.show();')
  lines.push('  FastLED.delay(16);')
  lines.push('}')
  lines.push('')
  return lines.join('\n')
}
