// What the parts on the bench physically are, imported from the modelled assets.
//
// The counterpart to `boardProfiles.ts`: a board knows its own size and render,
// and now so does every other part. Generated by `scripts/import-part-assets.py`
// from each asset's `part.json`, where `dimensionsMm` is verified against a
// datasheet or fabrication print rather than estimated.
//
// This exists because the app was guessing. It declared the MAX98357A at
// 17.8 x 13.2 mm against a real 17.78 x 25.4, and derived a ring's diameter as
// `N x 10 mm / pi`, which gives 25.5 mm for an 8-LED ring that measures 32.2 and
// 191 mm for a 60 that measures 158. The hardware view's whole promise is that a
// part is the size it is beside your board, so a remembered number is not a
// small inaccuracy — it is the view lying about the bench.

import { PART_CATALOGUE_DATA } from '../build/generated/partCatalogueData'

export type PartCategory =
  | 'microphone' | 'amplifier' | 'storage' | 'led-output'
  | 'input-control' | 'audio-source' | 'support' | 'display' | 'switching-power' | 'power-monitor' | 'power-conversion'
  | 'communication'

export interface PartRenderAsset {
  /** Path relative to the site root, e.g. `parts/max98357a-i2s-amplifier.webp`. */
  file: string
  widthPx: number
  heightPx: number
  /** Density the render actually achieved — below the 12 px/mm target for parts
   *  over ~100 mm, where the 1200 px cap wins. */
  pxPerMm?: number
}

/** The pixel geometry an LED output's asset was built for. */
export interface PartLedLayout {
  form: 'strip' | 'matrix' | 'ring' | 'hub75'
  count?: number
  width?: number
  height?: number
  diameterMm?: number
  /** Centre-to-centre LED spacing. 4 mm for a P4 HUB75 panel, 10 mm for a
   *  WS2812B matrix, 16.7 mm for a 60 LEDs/m strip. */
  pitchMm?: number
}

/**
 * The driver contract an auxiliary display's asset declares.
 *
 * Imported rather than hand-declared, for the same reason `dimensionsMm` is:
 * the app used to carry these numbers from memory and got them wrong. A
 * resolution typed into the app is a resolution that can disagree with the
 * panel on the bench, and every fixed layout is computed from it.
 */
export interface PartDisplaySpec {
  /** Exact controller, e.g. `SSD1306`, `ST7789`, `TM1637`. */
  controller: string
  /** Panel size in pixels. A 7-segment module reports digits x segments. */
  resolutionPx: [number, number]
  /** How the board talks to it, e.g. `I2C`, `SPI`, `CLK + DIO`. */
  interface: string
  /** Touch controller when one is fitted, else null. */
  touchController: string | null
  /**
   * How touch is read when there is no controller to name.
   *
   * `resistive-shared` is a bare sheet wired across four lines the LCD bus
   * already owns. It has no digitiser, so `touchController` is honestly null -
   * and a panel that asked only that question read this board as having no
   * touch at all and never emitted its read.
   */
  touchSurface?: 'resistive-shared' | null
}

/** Electrical identity carried by an imported relay-module asset. */
export interface PartRelaySpec {
  channels: number
  coilVoltage: string
  trigger: 'active-low' | 'active-high' | string
  contacts: string
  contactRating: string
  optoIsolated: boolean
}

/** Electrical identity carried by an imported DC MOSFET switch module. */
export interface PartMosfetSpec {
  channels: number
  device: string
  trigger: 'active-high' | 'active-low' | string
  /** The load-side supply the module switches, e.g. "6-28 V DC". */
  loadSupply: string
  continuousCurrent: string
  optoIsolated: boolean
  /** Whether the board carries its own flyback diode across the load. */
  flybackDiode: boolean
  /** Load-side terminals as printed, left to right in the render. */
  loadTerminals?: string[]
}

/** Measuring contract carried by an imported current/voltage monitor. */
export interface PartPowerMonitorSpec {
  device: string
  interface: string
  /** Every address the board's straps can select, as numbers. */
  i2cAddresses: number[]
  defaultI2cAddress: number
  /** The fitted shunt; firmware divides the shunt voltage by it. */
  shuntOhms: number
  busVoltageMaxV: number
  currentMaxA: number
  senseSide: 'high-side' | 'low-side' | string
}

/** Reporting contract carried by an imported radar presence sensor. */
export interface PartPresenceSensorSpec {
  device: string
  interface: string
  /** The rate the module streams its frames at; firmware opens the UART at it. */
  baud: number
  /** Width of one distance gate. */
  gateMeters: number
  /** The factory range, which the preview's distance slider spans. */
  maxRangeMeters: number
}

/** Measuring contract carried by an ambient-light sensor breakout. */
export interface PartLightSensorSpec {
  device: string
  interface: string
  i2cAddresses: number[]
  defaultI2cAddress: number
  /** Upper end of the ordinary high-resolution measurement range. */
  maxLux: number
}

/** Network contract carried by a wired-Ethernet controller module. */
export interface PartEthernetSpec {
  /** The controller chip, which picks the firmware's PHY driver. */
  controller: string
  interface: string
  /** The controller's SPI clock ceiling. */
  maxSpiClockMHz: number
  link: string
}

/** Physical contract for a matched long-range pixel-data TX/RX pair. */
export interface PartPixelDataExtenderSpec {
  mode: string
  maxDistanceMeters: number
  maxDataRateMbps: number
  supplyMinV: number
  supplyMaxV: number
  /** The conductors between the two modules, in the manufacturer's order. */
  pairConductors: string[]
}

/** A DC-DC converter between a 12/24 V source and a 5 V load. */
export interface PartPowerConverterSpec {
  /** `controller` powers only the controller and 5 V peripherals; `led-rail` is the LED supply. */
  role: 'controller' | 'led-rail'
  topology: string
  inputMinV: number
  inputMaxV: number
  /** How far the input must stay above the output (a buck's dropout). */
  minHeadroomV: number
  outputSetV: number
  continuousCurrentMa: number
  peakCurrentMa: number
  /** Used to size the source side conservatively. */
  typicalEfficiency: number
  /** An isolated converter's output negative must be bonded to the common ground. */
  isolated: boolean
  /** Adjustable output: it ships at an arbitrary voltage and must be set before use. */
  adjustable: boolean
}

export interface PartCatalogueEntry {
  partId: string
  label: string
  category?: PartCategory | string
  manufacturer?: string
  logicVoltage?: string
  /** Real size, datasheet-verified. The render's own axes: width across, height
   *  down, with the pin header along the bottom edge. */
  dimensionsMm: { width: number; height: number }
  pinLabelsLeftToRight?: string[]
  notes?: string[]
  ledLayout?: PartLedLayout
  /** Present exactly on switching-power relay modules. */
  relay?: PartRelaySpec
  /** Present exactly on DC MOSFET switch modules. */
  mosfet?: PartMosfetSpec
  /** Present exactly on current/voltage monitor modules. */
  powerMonitor?: PartPowerMonitorSpec
  /** Present exactly on radar presence sensors. */
  presenceSensor?: PartPresenceSensorSpec
  /** Present exactly on calibrated digital ambient-light sensors. */
  lightSensor?: PartLightSensorSpec
  /** Present exactly on wired-Ethernet controller modules. */
  ethernet?: PartEthernetSpec
  /** Present exactly on a matched differential pixel-data extender pair. */
  pixelDataExtender?: PartPixelDataExtenderSpec
  /** Present exactly on DC-DC converter modules. */
  powerConverter?: PartPowerConverterSpec
  /** Present exactly on the auxiliary-display parts. */
  display?: PartDisplaySpec
  render?: PartRenderAsset
}

export const PART_CATALOGUE: Record<string, PartCatalogueEntry> = PART_CATALOGUE_DATA

export function partById(partId: string): PartCatalogueEntry | undefined {
  return PART_CATALOGUE[partId]
}

/*
 * A graph property names an electrical role; a module prints the name its
 * manufacturer chose for that role. For example, the square ST7789 breakout
 * prints SCL/SDA/RST/BL for SPI SCK/MOSI/reset/backlight. Keep the aliases here
 * beside the catalogue boundary so every physical view can show the words a
 * person will actually find on the part.
 */
const PART_PIN_PROPERTY_ALIASES: Record<string, readonly string[]> = {
  clkPin: ['CLK', 'SCK', 'SCL'],
  dioPin: ['DIO', 'DATA', 'DIN'],
  dinPin: ['DIN', 'DATA', 'DIO'],
  // WIZnet prints the W5500's active-low lines with a trailing n.
  csPin: ['CS', 'LOAD', 'LCD_CS', 'SCNN'],
  // A parallel board silkscreens register-select as RS; it is the same signal
  // an SPI board prints DC, so one property carries both names.
  dcPin: ['DC', 'RS', 'LCD_RS'],
  resetPin: ['RST', 'RESET', 'RES', 'LCD_RST', 'RSTN'],
  intPin: ['INT', 'INTN', 'IRQ'],
  wrPin: ['WR', 'LCD_WR'],
  rdPin: ['RD', 'LCD_RD'],
  ...Object.fromEntries(
    // LCD_D0..LCD_D7 as a parallel board prints them.
    Array.from({ length: 8 }, (_, bit) => [`d${bit}Pin`, [`D${bit}`, `LCD_D${bit}`]]),
  ),
  sckPin: ['SCK', 'CLK', 'SCL', 'D0', 'SCLK'],
  mosiPin: ['MOSI', 'SDA', 'DIN', 'DATA', 'D1'],
  misoPin: ['MISO', 'DO'],
  backlightPin: ['BL', 'LED', 'LITE', 'BACKLIGHT'],
  // An I2C OLED is not always silkscreened SDA/SCL: Adafruit's SSD1306 breakout
  // prints the SPI names DATA and CLK on the same two lines it answers I2C on.
  sdaPin: ['SDA', 'DATA', 'DIN', 'D1'],
  sclPin: ['SCL', 'CLK', 'SCK', 'D0'],
  // The three I2S MEMS microphones print the same three signals under three
  // sets of names: an INMP441 says WS/SCK/SD, an Adafruit-form ICS-43434 says
  // LRCL/BCLK/DOUT, and the generic MSM261 boards follow the INMP441.
  i2sWs: ['WS', 'LRCL', 'LRCLK', 'LRC'],
  i2sSck: ['SCK', 'BCLK', 'BCK', 'CLK'],
  i2sSd: ['SD', 'DOUT', 'DATA', 'DO'],
  touchCsPin: ['T_CS'],
  touchIrqPin: ['T_IRQ'],
  touchSckPin: ['T_CLK'],
  touchMosiPin: ['T_DIN'],
  touchMisoPin: ['T_DO'],
  ...Object.fromEntries(
    Array.from({ length: 8 }, (_, index) => [`in${index + 1}Pin`, [`IN${index + 1}`]]),
  ),
}

/** The exact label printed on a catalogued part for one graph pin property. */
export function partPinLabelForProperty(partId: string, propertyKey: string): string | null {
  const labels = partById(partId)?.pinLabelsLeftToRight ?? []
  const aliases = PART_PIN_PROPERTY_ALIASES[propertyKey]
  if (!aliases) return null
  return labels.find((label) => aliases.includes(label.toUpperCase())) ?? null
}

/** The catalogued size, or `fallback` for a part not modelled yet. */
/**
 * Pads a two-board part carries on both boards and joins between them.
 *
 * The MAX98357A stereo pair prints each board's pads with an `L:` or `R:`
 * prefix. The bus, supply and ground are one net across both boards; a
 * board's own SD (which channel it plays) and GAIN are per-board settings and
 * are never bridged. Empty for any part that is a single board.
 */
const PER_BOARD_PADS = new Set(['SD', 'GAIN'])

export function sharedPadsAcrossBoards(partId: string): string[] {
  const pads = partById(partId)?.pinLabelsLeftToRight ?? []
  const left = pads.filter((pad) => pad.startsWith('L:')).map((pad) => pad.slice(2))
  const right = new Set(pads.filter((pad) => pad.startsWith('R:')).map((pad) => pad.slice(2)))
  return left.filter((pad) => right.has(pad) && !PER_BOARD_PADS.has(pad))
}

export function partDimensionsMm(
  partId: string,
  fallback: { width: number; height: number },
): { width: number; height: number } {
  return partById(partId)?.dimensionsMm ?? fallback
}

/** Site-root render path, or null while a part has no asset. */
export function partRenderSrc(partId: string): string | null {
  const file = partById(partId)?.render?.file
  return file ? `/${file}` : null
}

/**
 * Whether a catalogued part is an auxiliary display.
 *
 * Derived from the asset declaring a display spec rather than from a category
 * string, so the two cannot drift apart — the same reasoning
 * `isHardwareOnlyNodeType` uses in state/hardware.ts. A part either states its
 * controller and resolution or it is not a display.
 */
export function isDisplayPart(partId: string): boolean {
  return partById(partId)?.display !== undefined
}

/**
 * Whether a catalogued display can report a touch at all.
 *
 * Not the same question as which digitiser it uses. A bare resistive sheet has
 * no controller to name - it is two layers wired across lines the LCD bus
 * already owns - so `touchController` is honestly null on such a panel and
 * every reader that asked only that read it as having no touch. That is one
 * question with one answer, so it lives here rather than being spelled out at
 * each of the ten places that ask it.
 *
 * Two callers deliberately still ask the narrower question: the pin gate, for
 * which an SPI panel needs a digitiser before it has a touch *header* to wire,
 * and the hardware manifest, which records the controller's identity and for
 * which null is the truth.
 */
export function displayHasTouch(partId: string): boolean {
  const display = partById(partId)?.display
  return Boolean(display?.touchController || display?.touchSurface)
}

/** Every catalogued display, in catalogue order. */
export function catalogueDisplays(): PartCatalogueEntry[] {
  return Object.values(PART_CATALOGUE).filter((entry) => entry.display !== undefined)
}

/**
 * Catalogued displays that no part menu offers, and why each is held back.
 *
 * A modelled part is not the same as a drivable one. These have real assets,
 * measured dimensions and measured pad geometry, so they belong in the
 * catalogue - but listing one in a menu would be a claim the firmware cannot
 * keep, because nothing can generate a working sketch for it yet.
 *
 * Stated once because three places ask the question and they had drifted:
 * `displayPartCoverage.test.ts` (a rendered part must be offered or named
 * here), `hardwareRegistries.test.ts` (the same rule from the node side), and
 * `scripts/generate-display-smoke.ts` (which refuses to build a fixture set
 * that silently omits a part). Naming an id here rather than skipping
 * unoffered parts is what keeps a *newly* unoffered part a failure.
 *
 * - `ili9341-xpt2046-touch-320x240`: modelled but undriven.
 *
 * Remove an id the moment a build of that part can light up, not before.
 */
export const CATALOGUE_ONLY_DISPLAY_PART_IDS: readonly string[] = [
  'ili9341-xpt2046-touch-320x240',
]

/** The panel geometry a fixed layout is computed against. */
export function displayResolution(partId: string): { width: number; height: number } | null {
  const spec = partById(partId)?.display
  if (!spec) return null
  const [width, height] = spec.resolutionPx
  return { width, height }
}

/** Every catalogued ring, smallest first — the counts that were modelled. */
export function catalogueRings(): Array<{ count: number; diameterMm: number }> {
  return Object.values(PART_CATALOGUE)
    .filter((entry) => entry.ledLayout?.form === 'ring' && entry.ledLayout.count)
    .map((entry) => ({
      count: entry.ledLayout!.count!,
      diameterMm: entry.ledLayout!.diameterMm ?? entry.dimensionsMm.width,
    }))
    .sort((a, b) => a.count - b.count)
}

/**
 * How wide a ring of `ledCount` LEDs really is.
 *
 * Measured where the part exists — rings are sold in fixed counts and those are
 * the ones modelled (8, 12, 16, 24, 60) — and interpolated between neighbours
 * otherwise. It is deliberately not a formula: real rings are not linear in LED
 * count, because a small ring needs a minimum hub regardless of how few LEDs
 * sit on it. An 8-LED ring measures 32.2 mm where even pitch would predict 21.6,
 * and the old `N x 10 / pi` was wrong at both ends of the range.
 *
 * Outside the modelled range the nearest ring's pitch is held constant, which
 * is the honest extrapolation: beyond 60 LEDs the hub stops mattering and the
 * circumference is all that grows.
 */
export function ringDiameterMm(ledCount: number): number {
  const rings = catalogueRings()
  const count = Math.max(1, Math.round(ledCount))
  if (rings.length === 0) return Math.max(12, (count * 10) / Math.PI)

  const exact = rings.find((ring) => ring.count === count)
  if (exact) return exact.diameterMm

  const first = rings[0]
  const last = rings[rings.length - 1]
  if (count < first.count) return (first.diameterMm * count) / first.count
  if (count > last.count) return (last.diameterMm * count) / last.count

  for (let i = 0; i < rings.length - 1; i++) {
    const lo = rings[i]
    const hi = rings[i + 1]
    if (count >= lo.count && count <= hi.count) {
      const t = (count - lo.count) / (hi.count - lo.count)
      return lo.diameterMm + (t * (hi.diameterMm - lo.diameterMm))
    }
  }
  return last.diameterMm
}
