// What the parts on the bench physically are, imported from the modelled assets.
//
// The counterpart to `boardProfiles.ts`: a board knows its own size and render,
// and now so does every other part. Generated by `scripts/import-part-assets.py`
// from each asset's `part.json`, where `dimensionsMm` is verified against a
// datasheet or fabrication print rather than estimated.
//
// This exists because the app was guessing. It declared the MAX98357A at
// 17.8 x 13.2 mm against a real 17.78 x 25.4, and derived a ring's diameter as
// `N x 10 mm / pi`, which gives 25.5 mm for an 8-LED ring that measures 32.2 and
// 191 mm for a 60 that measures 158. The hardware view's whole promise is that a
// part is the size it is beside your board, so a remembered number is not a
// small inaccuracy — it is the view lying about the bench.

import { PART_CATALOGUE_DATA } from '../build/generated/partCatalogueData'

export type PartCategory =
  | 'microphone' | 'amplifier' | 'storage' | 'led-output'
  | 'input-control' | 'audio-source' | 'support'

export interface PartRenderAsset {
  /** Path relative to the site root, e.g. `parts/max98357a-i2s-amplifier.webp`. */
  file: string
  widthPx: number
  heightPx: number
  /** Density the render actually achieved — below the 12 px/mm target for parts
   *  over ~100 mm, where the 1200 px cap wins. */
  pxPerMm?: number
}

/** The pixel geometry an LED output's asset was built for. */
export interface PartLedLayout {
  form: 'strip' | 'matrix' | 'ring' | 'hub75'
  count?: number
  width?: number
  height?: number
  diameterMm?: number
  /** Centre-to-centre LED spacing. 4 mm for a P4 HUB75 panel, 10 mm for a
   *  WS2812B matrix, 16.7 mm for a 60 LEDs/m strip. */
  pitchMm?: number
}

/**
 * The driver contract an auxiliary display's asset declares.
 *
 * Imported rather than hand-declared, for the same reason `dimensionsMm` is:
 * the app used to carry these numbers from memory and got them wrong. A
 * resolution typed into the app is a resolution that can disagree with the
 * panel on the bench, and every fixed layout is computed from it.
 */
export interface PartDisplaySpec {
  /** Exact controller, e.g. `SSD1306`, `ST7789`, `TM1637`. */
  controller: string
  /** Panel size in pixels. A 7-segment module reports digits x segments. */
  resolutionPx: [number, number]
  /** How the board talks to it, e.g. `I2C`, `SPI`, `CLK + DIO`. */
  interface: string
  /** Touch controller when one is fitted, else null. */
  touchController: string | null
}

export interface PartCatalogueEntry {
  partId: string
  label: string
  category?: PartCategory | string
  manufacturer?: string
  logicVoltage?: string
  /** Real size, datasheet-verified. The render's own axes: width across, height
   *  down, with the pin header along the bottom edge. */
  dimensionsMm: { width: number; height: number }
  pinLabelsLeftToRight?: string[]
  notes?: string[]
  ledLayout?: PartLedLayout
  /** Present exactly on the auxiliary-display parts. */
  display?: PartDisplaySpec
  render?: PartRenderAsset
}

export const PART_CATALOGUE: Record<string, PartCatalogueEntry> = PART_CATALOGUE_DATA

export function partById(partId: string): PartCatalogueEntry | undefined {
  return PART_CATALOGUE[partId]
}

/** The catalogued size, or `fallback` for a part not modelled yet. */
export function partDimensionsMm(
  partId: string,
  fallback: { width: number; height: number },
): { width: number; height: number } {
  return partById(partId)?.dimensionsMm ?? fallback
}

/** Site-root render path, or null while a part has no asset. */
export function partRenderSrc(partId: string): string | null {
  const file = partById(partId)?.render?.file
  return file ? `/${file}` : null
}

/**
 * Whether a catalogued part is an auxiliary display.
 *
 * Derived from the asset declaring a display spec rather than from a category
 * string, so the two cannot drift apart — the same reasoning
 * `isHardwareOnlyNodeType` uses in state/hardware.ts. A part either states its
 * controller and resolution or it is not a display.
 */
export function isDisplayPart(partId: string): boolean {
  return partById(partId)?.display !== undefined
}

/** Every catalogued display, in catalogue order. */
export function catalogueDisplays(): PartCatalogueEntry[] {
  return Object.values(PART_CATALOGUE).filter((entry) => entry.display !== undefined)
}

/** The panel geometry a fixed layout is computed against. */
export function displayResolution(partId: string): { width: number; height: number } | null {
  const spec = partById(partId)?.display
  if (!spec) return null
  const [width, height] = spec.resolutionPx
  return { width, height }
}

/** Every catalogued ring, smallest first — the counts that were modelled. */
export function catalogueRings(): Array<{ count: number; diameterMm: number }> {
  return Object.values(PART_CATALOGUE)
    .filter((entry) => entry.ledLayout?.form === 'ring' && entry.ledLayout.count)
    .map((entry) => ({
      count: entry.ledLayout!.count!,
      diameterMm: entry.ledLayout!.diameterMm ?? entry.dimensionsMm.width,
    }))
    .sort((a, b) => a.count - b.count)
}

/**
 * How wide a ring of `ledCount` LEDs really is.
 *
 * Measured where the part exists — rings are sold in fixed counts and those are
 * the ones modelled (8, 12, 16, 24, 60) — and interpolated between neighbours
 * otherwise. It is deliberately not a formula: real rings are not linear in LED
 * count, because a small ring needs a minimum hub regardless of how few LEDs
 * sit on it. An 8-LED ring measures 32.2 mm where even pitch would predict 21.6,
 * and the old `N x 10 / pi` was wrong at both ends of the range.
 *
 * Outside the modelled range the nearest ring's pitch is held constant, which
 * is the honest extrapolation: beyond 60 LEDs the hub stops mattering and the
 * circumference is all that grows.
 */
export function ringDiameterMm(ledCount: number): number {
  const rings = catalogueRings()
  const count = Math.max(1, Math.round(ledCount))
  if (rings.length === 0) return Math.max(12, (count * 10) / Math.PI)

  const exact = rings.find((ring) => ring.count === count)
  if (exact) return exact.diameterMm

  const first = rings[0]
  const last = rings[rings.length - 1]
  if (count < first.count) return (first.diameterMm * count) / first.count
  if (count > last.count) return (last.diameterMm * count) / last.count

  for (let i = 0; i < rings.length - 1; i++) {
    const lo = rings[i]
    const hi = rings[i + 1]
    if (count >= lo.count && count <= hi.count) {
      const t = (count - lo.count) / (hi.count - lo.count)
      return lo.diameterMm + (t * (hi.diameterMm - lo.diameterMm))
    }
  }
  return last.diameterMm
}
