[env:esp32_esp32_esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_flags = -DCORE_DEBUG_LEVEL=0

[env:esp32_esp32_esp32s3_opi]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_flags = -DCORE_DEBUG_LEVEL=0 -DBOARD_HAS_PSRAM
board_build.arduino.memory_type = qio_opi

[env:esp32_esp32_esp32s3_qspi]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_flags = -DCORE_DEBUG_LEVEL=0 -DBOARD_HAS_PSRAM
board_build.arduino.memory_type = qio_qspi

[env:esp32_esp32_esp32]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DCORE_DEBUG_LEVEL=0

[env:esp32_esp32_esp32_qspi]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DCORE_DEBUG_LEVEL=0 -DBOARD_HAS_PSRAM
board_build.arduino.memory_type = qio_qspi

[env:arduino_avr_uno]
platform = atmelavr
board = uno
framework = arduino

[env:arduino_avr_nano]
platform = atmelavr
board = nanoatmega328new
framework = arduino

[env:teensy_avr_teensy41]
platform = teensy
board = teensy41
framework = arduino

[env:rp2040_rp2040_rpipico]
platform = raspberrypi
board = pico
framework = arduino
